MSG_KEY['ACC_NO'] = 'Account No.';
MSG_KEY['ADDR'] = 'Address';
MSG_KEY['AMS_CD'] = 'AMS Code';
MSG_KEY['APPLY_DATE'] = 'Apply Date';
MSG_KEY['APPLY_SCOPE'] = 'Apply Scope';
MSG_KEY['BIZ_TYPE'] = 'Biz. Type';
MSG_KEY['BKG_STATUS'] = 'Booking Status';
MSG_KEY['CEO'] = 'CEO';
MSG_KEY['CNT'] = 'Country';
MSG_KEY['CNT_CD'] = 'Country Code';
MSG_KEY['CONT'] = 'Content';
MSG_KEY['CONTI_CD'] = 'Continent Code';
MSG_KEY['CTRB_MGN'] = 'Contribution Margin';
MSG_KEY['CURR'] = 'Currency';
MSG_KEY['DATE'] = 'Date';
MSG_KEY['DAY_MONTH'] = 'Day/Month Type';
MSG_KEY['DESC'] = 'Description';
MSG_KEY['DESC'] = 'Description';
MSG_KEY['DIV'] = 'Division';
MSG_KEY['DUR_HOUR'] = 'Duration(Hour)';
MSG_KEY['EMAIL'] = 'EMail'
MSG_KEY['ENG_ADDR'] = 'Eng. Address';
MSG_KEY['ENG_NM'] = 'Name(Eng.)';
MSG_KEY['FAX'] = 'Fax';
MSG_KEY['FINC_OFC'] = 'Finnance Office';
MSG_KEY['FM_CURR_CD'] = 'From Currency';
MSG_KEY['FMS_COD_ACCT'] = 'Account ';
MSG_KEY['FMS_COD_ADDR'] = 'Address ';
MSG_KEY['FMS_COD_AGENTNM'] = 'Agent Name';
MSG_KEY['FMS_COD_AGNT'] = 'Agent ';
MSG_KEY['FMS_COD_AIRL'] = 'Airline ';
MSG_KEY['FMS_COD_AMT'] = 'Amount ';
MSG_KEY['FMS_COD_ARRV'] = 'Arrival ';
MSG_KEY['FMS_COD_ASHP'] = 'AShipper ';
MSG_KEY['FMS_COD_BANKNM'] = 'Bank Name';
MSG_KEY['FMS_COD_BATTYPE'] = 'Batch Type';
MSG_KEY['FMS_COD_BILL'] = 'Billing ';
MSG_KEY['FMS_COD_BILLCOST'] = 'Cost Code ';
MSG_KEY['FMS_COD_BILLCRDB'] = 'CR/DB Code ';
MSG_KEY['FMS_COD_BILLINGCODE'] = 'Billing Code';
MSG_KEY['FMS_COD_BILLINGINFO'] = 'Billing Information';
MSG_KEY['FMS_COD_BILLREV'] = 'Revenue Code ';
MSG_KEY['FMS_COD_BLCURRENCY'] = 'B/L Currency ';
MSG_KEY['FMS_COD_BLNO'] = 'B/L No. ';
MSG_KEY['FMS_COD_BLTO'] = 'Bill To ';
MSG_KEY['FMS_COD_BOND'] = 'Bond ';
MSG_KEY['FMS_COD_BUCR'] = 'Buying/Credit ';
MSG_KEY['FMS_COD_BUPN'] = 'Buyer PO No. ';
MSG_KEY['FMS_COD_CAGMEAS'] = 'Cargo Measurement';
MSG_KEY['FMS_COD_CAGWEIG'] = 'Cargo Weight';
MSG_KEY['FMS_COD_CARR'] = 'Carrier ';
MSG_KEY['FMS_COD_CBKNO'] = 'Carrier BKG No. ';
MSG_KEY['FMS_COD_CLRDT'] = 'Deposit/Clear Date';
MSG_KEY['FMS_COD_CMDT'] = 'Commodity ';
MSG_KEY['FMS_COD_CMDTCD'] = 'Commodity Code';
MSG_KEY['FMS_COD_CNEE'] = 'Consignee';
MSG_KEY['FMS_COD_CNTR'] = 'Container ';
MSG_KEY['FMS_COD_CNTRQTY'] = 'Container Quantity ';
MSG_KEY['FMS_COD_CNTRCD'] = 'Container Code';
MSG_KEY['FMS_COD_CNTY'] = 'Country ';
MSG_KEY['FMS_COD_CODE'] = 'Code ';
MSG_KEY['FMS_COD_CONS'] = 'Console ';
MSG_KEY['FMS_COD_CONT'] = 'Continent ';
MSG_KEY['FMS_COD_CRDB'] = 'CR/DB ';
MSG_KEY['FMS_COD_CUPN'] = 'Customer PO No. ';
MSG_KEY['FMS_COD_CURR'] = 'Currency ';
MSG_KEY['FMS_COD_CUST'] = 'Customer ';
MSG_KEY['FMS_COD_CUSTIT'] = 'Customer Item ';
MSG_KEY['FMS_COD_DATE'] = 'Date ';
MSG_KEY['FMS_COD_DATM'] = 'Date & Time ';
MSG_KEY['FMS_COD_DEBK'] = 'Deposit Bank ';
MSG_KEY['FMS_COD_DEL_ETA_'] = 'DELIVERY ETA ';
MSG_KEY['FMS_COD_DESC'] = 'Description ';
MSG_KEY['FMS_COD_DETP'] = 'Department Type ';
MSG_KEY['FMS_COD_DOCTO'] = 'Document To';
MSG_KEY['FMS_COD_DUEDT'] = 'Due Date ';
MSG_KEY['FMS_COD_EDNDT'] = 'Ending Date';
MSG_KEY['FMS_COD_ENGN'] = 'English Name ';
MSG_KEY['FMS_COD_ETA_'] = 'ETA ';
MSG_KEY['FMS_COD_ETD_'] = 'ETD ';
MSG_KEY['FMS_COD_EXRT'] = 'Exchange Rate ';
MSG_KEY['FMS_COD_FINO'] = 'Filing No. ';
MSG_KEY['FMS_COD_FLIT'] = 'Flight ';
MSG_KEY['FMS_COD_FRET'] = 'Freight ';
MSG_KEY['FMS_COD_GL'] = 'G/L Code';
MSG_KEY['FMS_COD_GLNO'] = 'G/L No. ';
MSG_KEY['FMS_COD_EXPRGL'] = 'Exchange Profit G/L No. ';
MSG_KEY['FMS_COD_EXLOGL'] = 'Exchange Loss G/L No. ';
MSG_KEY['FMS_COD_GWGT'] = 'Gross Weight ';
MSG_KEY['FMS_COD_HANO'] = 'HAWB No. ';
MSG_KEY['FMS_COD_HAWB'] = 'HAWB ';
MSG_KEY['FMS_COD_HBL_'] = 'HB/L ';
MSG_KEY['FMS_COD_HBNO'] = 'HB/L No. ';
MSG_KEY['FMS_COD_HSN_'] = 'HSN (HB/L Sequence No.) ';
MSG_KEY['FMS_COD_IATA'] = 'IATA ';
MSG_KEY['FMS_COD_IDTP'] = 'ID TYPE ';
MSG_KEY['FMS_COD_IEXR'] = 'Invoice Exchange Rate ';
MSG_KEY['FMS_COD_INVOICEDT'] = 'Invoice Date ';
MSG_KEY['FMS_COD_IVNO'] = 'Invoice No. ';
MSG_KEY['FMS_COD_LINE'] = 'Liner ';
MSG_KEY['FMS_COD_LOCA'] = 'Location ';
MSG_KEY['FMS_COD_LOCN'] = 'Local Name ';
MSG_KEY['FMS_COD_MAIL'] = 'EMail Address ';
MSG_KEY['FMS_COD_MAWB'] = 'MAWB ';
MSG_KEY['FMS_COD_MBLN'] = 'MB/L No. ';
MSG_KEY['FMS_COD_MEAS'] = 'Measurement ';
MSG_KEY['FMS_COD_MISCFILNO'] = 'MISC. Filing No.';
MSG_KEY['FMS_COD_MRNO'] = 'MRN (Manifest Reference No.) ';
MSG_KEY['FMS_COD_MSNO'] = 'MSN (MB/L Sequence No.) ';
MSG_KEY['FMS_COD_NAME'] = 'Name ';
MSG_KEY['FMS_COD_NTFY'] = 'Notify ';
MSG_KEY['FMS_COD_NULL'] = '   '; //임시
MSG_KEY['FMS_COD_NUM_'] = 'No. ';
MSG_KEY['FMS_COD_OCUR'] = 'One Currency ';
MSG_KEY['FMS_COD_OFCE'] = 'Office ';
MSG_KEY['FMS_COD_ORDT'] = 'Order Date ';
MSG_KEY['FMS_COD_PARA'] = '@'; //FMS에서는 #param1#가 아닌 @로 정의 (CoBizCommon.js)
MSG_KEY['FMS_COD_PAYTO'] = 'Paid To';
MSG_KEY['FMS_COD_PERDT'] = 'Period Date';
MSG_KEY['FMS_COD_PEXR'] = 'Performance Exchange Rate ';
MSG_KEY['FMS_COD_PKGE'] = 'Package ';
MSG_KEY['FMS_COD_PKGECD'] = 'Package Code ';
MSG_KEY['FMS_COD_POLC'] = 'POL ';
MSG_KEY['FMS_COD_POST'] = 'Post ';
MSG_KEY['FMS_COD_POSTDT'] = 'Post Date';
MSG_KEY['FMS_COD_POSTING'] = 'Posting Date ';
MSG_KEY['FMS_COD_PROCEDT'] = 'Processing Date';
MSG_KEY['FMS_COD_PSHARE'] = 'Profit Share';
MSG_KEY['FMS_COD_QTY'] = 'QTY';
MSG_KEY['FMS_COD_RATE'] = 'Rate ';
MSG_KEY['FMS_COD_RECEIVED'] = 'Received';
MSG_KEY['FMS_COD_RECEIVER'] = 'Receiver';
MSG_KEY['FMS_COD_RECP'] = 'W/H Receipt No.';
MSG_KEY['FMS_COD_REFN'] = 'Filing No. ';
MSG_KEY['FMS_COD_REVFM'] = 'Received From';
MSG_KEY['FMS_COD_REVAMT'] = 'Received Amount';
MSG_KEY['FMS_COD_RMK'] = 'Remark ';
MSG_KEY['FMS_COD_RPLT'] = 'Report List ';
MSG_KEY['FMS_COD_RPTT'] = 'Report Type ';
MSG_KEY['FMS_COD_SAGT'] = 'Sub Agent ';
MSG_KEY['FMS_COD_SEDE'] = 'Selling/Debit ';
MSG_KEY['FMS_COD_SENDDT'] = 'Send Date';
MSG_KEY['FMS_COD_SHIP'] = 'Shipper';
MSG_KEY['FMS_COD_SHPW'] = 'Ship Window ';
MSG_KEY['FMS_COD_SHTO'] = 'Ship To ';
MSG_KEY['FMS_COD_SINO'] = 'S/I No.';
MSG_KEY['FMS_COD_SLNO'] = 'Slip No.';
MSG_KEY['FMS_COD_SUBC'] = 'Sub-Continent ';
MSG_KEY['FMS_COD_SZUN'] = 'Size Unit ';
MSG_KEY['FMS_COD_TCUR'] = 'To Currency ';
MSG_KEY['FMS_COD_TERM'] = 'SVC Term ';
MSG_KEY['FMS_COD_TO'] = 'To';
MSG_KEY['FMS_COD_TPSZ'] = 'Type/Size ';
MSG_KEY['FMS_COD_TRPT'] = 'Trade Partner ';
MSG_KEY['FMS_COD_TYPE'] = 'Type ';
MSG_KEY['FMS_COD_UDFCD'] = 'User Define Field ';
MSG_KEY['FMS_COD_UNTP'] = 'Unit Type ';
MSG_KEY['FMS_COD_USPP'] = 'USPPI Phone No. ';
MSG_KEY['FMS_COD_VENDOR'] = 'Vendor';
MSG_KEY['FMS_COD_VESL'] = 'Vessel ';
MSG_KEY['FMS_COD_VOLM'] = 'Volume ';
MSG_KEY['FMS_COD_VOYA'] = 'Voyage ';
MSG_KEY['FMS_COD_WMFILNO'] = 'Warehouse Doc. Filing No.';
MSG_KEY['FMS_COD_WONO'] = 'W/O No. ';
MSG_KEY['FMS_COD_TMZN'] = 'Time Zone ';
MSG_KEY['FMS_COM_000000'] = 'Refine This Message!!! ';
MSG_KEY['FMS_COM_000001'] = 'The B/L( MBL NO : @ ) Information already exists.';
MSG_KEY['FMS_COM_ALT001'] = 'Please enter a Mandatory Value!'; //(Red indicates required field) //+CODE
MSG_KEY['FMS_COM_ALT002'] = 'Please enter a Value correctly! '; //NO or WRONG DATA INPUT. +MSG, CODE
MSG_KEY['FMS_COM_ALT003'] = 'Please select only one Data! ';
MSG_KEY['FMS_COM_ALT004'] = 'Please select Data! ';
MSG_KEY['FMS_COM_ALT005'] = 'Only Numbers are available! ';
MSG_KEY['FMS_COM_ALT006'] = 'Please enter a Value first! '; //+MSG
MSG_KEY['FMS_COM_ALT007'] = 'Please check the Data! '; //SOMETHING WRONG FOR CALCULATION OR GIVEN DATA. +CODE, ROW
MSG_KEY['FMS_COM_ALT008'] = 'Duplicated Data! '; //+CODE, ROW
MSG_KEY['FMS_COM_ALT009'] = 'No data to save! ';
MSG_KEY['FMS_COM_ALT010'] = 'No Data found! '; //+CODE
MSG_KEY['FMS_COM_ALT011'] = 'Cannot delete! '; //+
MSG_KEY['FMS_COM_ALT012'] = 'Already completed! '; //+
MSG_KEY['FMS_COM_ALT013'] = 'Already exist Data! '; //+
MSG_KEY['FMS_COM_ALT014'] = 'Please enter a Search Condition! '; //+MSG
MSG_KEY['FMS_COM_ALT015'] = 'Please Save first! '; //+
MSG_KEY['FMS_COM_ALT016'] = 'Please Issue first! '; //+
MSG_KEY['FMS_COM_ALT017'] = 'Deleted Data! '; //+
MSG_KEY['FMS_COM_ALT018'] = 'Modified Data! '; //+
MSG_KEY['FMS_COM_ALT019'] = 'Failed! '; //+
MSG_KEY['FMS_COM_ALT020'] = 'COD(Cash On Delivery) Case!'; //COD(Cash On Delivery) 입니다!
MSG_KEY['FMS_COM_ALT021'] = '[Warning] ETD or ETA is allowed within 6 months! '; //EDT 혹은 ETA는 6개월 이내로 입력해야 합니다!
MSG_KEY['FMS_COM_ALT022'] = 'Cannot delete because Invoice has been issued already.'; //Invoice가 Issue 상태이기 때문에 삭제할 수 없습니다!
MSG_KEY['FMS_COM_ALT023'] = 'Please change the Split Shipment flag to Yes! '; //분할선적 여부를 Yes로 변경해 주세요!
MSG_KEY['FMS_COM_ALT024'] = 'Cannot enter a Value when the Split Shipment flag is No! '; //분할선적 여부가 No이므로 입력할 수 없습니다!
MSG_KEY['FMS_COM_ALT025'] = 'Data already used! '; //+
MSG_KEY['FMS_COM_ALT026'] = 'Please delete the HB/L in advance.';
MSG_KEY['FMS_COM_ALT027'] = 'You cannot upload this file! Permitted file extensions are as follows: \n'; //파일을 업로드할 수 없습니다! 업로드 가능한 파일 확장자:
MSG_KEY['FMS_COM_ALT028'] = 'No changed data! '; //+CODE
MSG_KEY['FMS_COM_ALT029'] = 'Please Retrieve first! ';
MSG_KEY['FMS_COM_ALT030'] = '\n(The Max. Length of this field is @.)';
MSG_KEY['FMS_COM_ALT031'] = 'Please enter a Value more than 7 characters! '; //+CODE
MSG_KEY['FMS_COM_ALT032'] = '@Invoice already created.';
MSG_KEY['FMS_COM_ALT033'] = 'End date must be greater than start date';
MSG_KEY['FMS_COM_ALT034'] = 'Accounting Closed. You can only edit following fields.\nShipper / Consignee / Notify Party / POL / POD / DEL / B/L Body.';
MSG_KEY['FMS_COM_ALT035'] = 'There is no House B/L data! ';
MSG_KEY['FMS_COM_ALT036'] = 'Please save first! ';
MSG_KEY['FMS_COM_ALT037'] = 'Please enter in a Search Value!!';
MSG_KEY['FMS_COM_ALT038'] = 'No content to save.';
MSG_KEY['FMS_COM_ALT039'] = 'Please search first.';
MSG_KEY['FMS_COM_ALT040'] = 'Please check date format.';
MSG_KEY['FMS_COM_ALT041'] = 'Year must be greater than 1900.';
MSG_KEY['FMS_COM_ALT042'] = 'Input data must be greater than 0.';
MSG_KEY['FMS_COM_ALT043'] = 'There is no Master B/L data! ';
MSG_KEY['FMS_COM_ALT044'] = "Payment can't be  0. ";
MSG_KEY['FMS_COM_ALT045'] = "Received can't be  0. ";
MSG_KEY['FMS_COM_ALT046'] = 'Please select a Container! '; //+Container
MSG_KEY['FMS_COM_ALT047'] = 'Please Enter MAWB No! '; //+MAWB No
MSG_KEY['FMS_COM_ALT048'] = "You don't have the role for the Linked Program"; //System > Admin > Role/Screen Mapping
MSG_KEY['FMS_COM_ALT049'] = 'Please select a MBL No! '; //+MBL
MSG_KEY['FMS_COM_ALT050'] = 'Please select a MAWB No! '; //+MAWB
MSG_KEY['FMS_COM_ALT051'] = 'There is no (Master B/L or Container) data! ';
MSG_KEY['FMS_COM_ALT052'] = 'There is no MAWB data! ';
MSG_KEY['FMS_COM_ALT053'] = 'There is no Other Filling No data! ';
MSG_KEY['FMS_COM_ALT054'] = 'There is no D/C Entry data! ';
MSG_KEY['FMS_COM_ALT055'] = 'Please check Report By Info! ';
MSG_KEY['FMS_COM_ALT056'] = 'MAIL Send Success';
MSG_KEY['FMS_COM_ALT057'] = 'FAX Send Success';
MSG_KEY['FMS_COM_ALT058'] = 'There is no MBL data! ';
MSG_KEY['FMS_COM_ALT059'] = 'You cannot upload this file!';
MSG_KEY['FMS_COM_ALT060'] = 'You cannot add invoice!. The account has been closed! ';
MSG_KEY['FMS_COM_ALT061'] = 'Please check a For Infomation! ';
MSG_KEY['FMS_COM_ALT062'] = 'CCN No. already exists.\nDo you want to change it? ';
MSG_KEY['FMS_COM_ALT063'] = '[warning] Duplicated CCN number found.';
MSG_KEY['FMS_COM_ALT064'] = 'Cannot create the invoice with prepaid item';
MSG_KEY['FMS_COM_ALT065'] = 'Filing No. do not exist!';
MSG_KEY['FMS_COM_ALT066'] = 'Invalid Filing No. Please save after check Filing No!';
MSG_KEY['FMS_COM_ALT067'] = 'The File does not exist';
MSG_KEY['FMS_COM_ALT068'] = 'Cannot delete because HB/L was Created! '; //HB/L이 Create 상태이기 때문에 삭제할 수 없습니다!
MSG_KEY['FMS_COM_ALT069'] = 'Cannot modify because HB/L was Created! '; //HB/L이 Create 상태이기 때문에 수정할 수 없습니다!
MSG_KEY['FMS_COM_ALT070'] = 'HB/L already created.';
MSG_KEY['FMS_COM_ALT071'] = 'Invalid Booking No. HB/L already created!';
MSG_KEY['FMS_COM_ALT072'] = 'Duplicated B/L Serial No. found.';
MSG_KEY['FMS_COM_ALT073'] = 'Cannot change PO Status because @!';
MSG_KEY['FMS_COM_ALT074'] = 'Cannot delete Item [@] because the item was used!';
MSG_KEY['FMS_COM_ALT075'] = 'You cannot enter a different Contribution Office for the same customers.';
MSG_KEY['FMS_COM_ALT076'] = 'Input data must be less than @.';
MSG_KEY['FMS_COM_ALT077'] = '\n(The Min. Length of this field is @.)';
MSG_KEY['FMS_COM_ALT078'] = 'Changing "Prefix/Sequence" during business hours can cause "duplicated" sequence. \n\nAre you sure you want to Continue?';
MSG_KEY['FMS_COM_ALT079'] = 'Changed "Prefix/Sequence" will not be saved. \n\nAre you sure you want to Continue?';
MSG_KEY['FMS_COM_ALT080'] = 'There is no vendor E-mail data! ';
MSG_KEY['FMS_COM_ALT081'] = 'Input data must be smaller than 0.';
MSG_KEY['FMS_COM_ALT082'] = '[Warning] @ is allowed within @ days! ';
MSG_KEY['FMS_COM_ALT083'] = "You are not able to save the data, since you don't have an authority.";
MSG_KEY['FMS_COM_ALT084'] = "You are not able to delete the data, since you don't have an authority.";
MSG_KEY['FMS_COM_ALT085'] = ' data must be less than @.';
MSG_KEY['FMS_COM_ALT086'] = 'Please register the VAT code in the following screen.\n(Code > MDM > Billing Code)\n(@ : @ (@%)). ';
MSG_KEY['FMS_COM_ALT087'] = "The period between \'From Date\' and \'To Date\'\nshould be within @ days! ";
MSG_KEY['FMS_COM_ALT088'] = 'There are too many trade partners.\nPlease add the search condition.';
MSG_KEY['FMS_COM_ALT089'] = 'Please choose and check only one rep. in Contact person information.';
MSG_KEY['FMS_COM_ALT090'] = 'MAWB No. is duplicated! '; //+CODE, ROW
MSG_KEY['FMS_COM_ALT091'] = 'Please enter a Value correctly! (Between @ ~ @) ';
MSG_KEY['FMS_COM_ALT092'] = 'Cannot delete because MB/L was Created! ';
MSG_KEY['FMS_COM_ALT093'] = 'Cannot modify because MB/L was Created! ';
MSG_KEY['FMS_COM_ALT094'] = 'Since invoice was generated, Filing No. cannot be modified.';
MSG_KEY['FMS_COM_ALT095'] = 'MB/L already created.';
MSG_KEY['FMS_COM_ALT096'] = 'Invalid Carrier Booking No. MB/L already created!';
MSG_KEY['FMS_COM_ALT097'] = 'Please input the date ranges!';
MSG_KEY['FMS_COM_ALT098'] = 'Finance Exchange Rate for selected date already exists. Please check and select another date.';
MSG_KEY['FMS_COM_ALT099'] = 'Exchange Rate for selected date already exists. Please check and select another date.';
MSG_KEY['FMS_COM_ALT100'] = 'Please, define a container on the Carrier Booking first.';
MSG_KEY['FMS_COM_ALT101'] = 'There is no invoice data! ';
MSG_KEY['FMS_COM_CFMCAN'] = 'Are you sure you want to Cancel? ';
MSG_KEY['FMS_COM_CFMCFM'] = 'Do you want to Confirm? ';
MSG_KEY['FMS_COM_CFMCLS'] = 'Do you want to Close? ';
MSG_KEY['FMS_COM_CFMCON'] = 'Are you sure you want to Continue? ';
MSG_KEY['FMS_COM_CFMCPY'] = 'Do you want to Copy? ';
MSG_KEY['FMS_COM_CFMCRE'] = 'Do you want to Create? ';
MSG_KEY['FMS_COM_CFMDEL'] = 'Are you sure you want to Delete? ';
MSG_KEY['FMS_COM_CFMDOWNINTERFACE'] = 'Do you want to download Interface Data? ';
MSG_KEY['FMS_COM_CFMGRS'] = 'The Gross Weight is Zero.\n Process Anyway?';
MSG_KEY['FMS_COM_CFMISS'] = 'Do you want to Issue? ';
MSG_KEY['FMS_COM_CFMMBLCRE'] = 'Filing No. does not exist. \n\nDo you want to Create MB/L & Save HB/L ?';
MSG_KEY['FMS_COM_CFMMEAS'] = 'The Measurement is Zero.\n Process Anyway?';
MSG_KEY['FMS_COM_CFMMOD'] = 'Do you want to Modify? ';
MSG_KEY['FMS_COM_CFMNEW'] = 'Are you sure you want to create new? ';
MSG_KEY['FMS_COM_CFMPRO'] = 'Do you want to proceed?';
MSG_KEY['FMS_COM_CFMRCV'] = 'Do you want to Receive? ';
MSG_KEY['FMS_COM_CFMSAV'] = 'Do you want to Save? ';
MSG_KEY['FMS_COM_CFMSAVCLS'] = 'Do you want to Save and Close the current Tab? ';
MSG_KEY['FMS_COM_CFMSEN'] = 'Do you want to Send? ';
MSG_KEY['FMS_COM_CFMSENDEDI'] = 'Do you want to Send EDI? ';
MSG_KEY['FMS_COM_CFMSENDEML'] = 'Do you want to send an Email? ';
MSG_KEY['FMS_COM_CFMSENDFAX'] = 'Do you want to Send a Fax? ';
MSG_KEY['FMS_COM_CFMVSL'] = 'Are you sure?  Selected Master B/Ls and connected House B/Ls Information will be updated.';
MSG_KEY['FMS_COM_CFMPRNBLCK'] = 'Do you want to Print and Block? ';
MSG_KEY['FMS_COM_CFMSAVBLCK'] = 'Do you want to Save and Block?  ';
MSG_KEY['FMS_COM_DUP_CNTC'] = 'This customer has been updated by other transactions.\nPlease reload ';
MSG_KEY['FMS_COM_DUP_MBL_HBL'] = 'There are duplicated BL No'; //+
MSG_KEY['FMS_COM_DUP_PHONE'] = 'There are duplicated Phone or Cell Phone Number.\nDo you want to save? '; //+
MSG_KEY['FMS_COM_ERR001'] = 'System Error! \n'; //+ err.message
MSG_KEY['FMS_COM_ERR002'] = 'Unexpected Error occurred. Please Contact Help Desk!'; //+ err.message
MSG_KEY['FMS_COM_ERR003'] = 'Value exceeds the maximum number of characters: Warehouse Config[200]!'; //+ err.message
MSG_KEY['FMS_COM_IP_CHK'] = "You are not allowed to set your IP address immediately after '*'";
MSG_KEY['FMS_COM_IS_USER'] = 'There are user(s) assigned to this Office Code. Please change their Office information before disabling this Office.';
MSG_KEY['FMS_COM_MSGCREATE'] = 'System property files will be overwritten.\nDo you want to continue? ';
MSG_KEY['FMS_COM_NOTISAV'] = 'Are you sure you want to send an E-mail Notification? \n If you select [Yes] then it will send PO registration notification to vendor. If you want to send PO registration notification later, please select [No].';
MSG_KEY['FMS_COM_NTYCOM'] = 'Completed! '; //Saved Successfully
MSG_KEY['FMS_COM_NTYDEL'] = 'Delete completed! '; //Saved Successfully
MSG_KEY['FMS_COM_NTYSAV'] = 'Save completed! '; //Saved Successfully
MSG_KEY['FMS_COM_SYS_OFC_CD'] = 'Office Code is assigned as default System Office Code. Please change the default System Office Code before disabling this Office.';
MSG_KEY['FMS_COM_WHSAV'] = 'You must choose the warehouse information list! '; //Saved Successfully
MSG_KEY['FRT_TERM_CD'] = 'Freight Term Type';
MSG_KEY['FULL_NM'] = 'Full Name';
MSG_KEY['HOL'] = 'Holder';
MSG_KEY['ICAO'] = 'ICAO';
MSG_KEY['INTER_RMK'] = 'Internal Remark';
MSG_KEY['IP_ADDR'] = 'IP Address';
MSG_KEY['ITEM'] = 'Item';
MSG_KEY['ITM_ADDR'] = 'Address';
MSG_KEY['ITM_ADDR'] = 'Address';
MSG_KEY['ITM_AGING_TP'] = 'Aging Report Type';
MSG_KEY['ITM_BANK'] = 'Bank';
MSG_KEY['ITM_CD'] = 'Code';
MSG_KEY['ITM_CDLEN'] = 'Code Length';
MSG_KEY['ITM_CDNM'] = 'Code Name';
MSG_KEY['ITM_CDORD'] = 'Code Order';
MSG_KEY['ITM_COUNTRY'] = 'Country';
MSG_KEY['ITM_DEPARTMEMT'] = 'Department';
MSG_KEY['ITM_DESC'] = 'Description';
MSG_KEY['ITM_EML'] = 'EMail';
MSG_KEY['ITM_EXPDT'] = 'Expire date';
MSG_KEY['ITM_EXTEML'] = 'External EMail';
MSG_KEY['ITM_EXTPWD'] = 'External EMail Passwords';
MSG_KEY['ITM_FRT_CD'] = 'Freight Code';
MSG_KEY['ITM_FRT_CD'] = 'Freight Code';
MSG_KEY['ITM_FRT_CD'] = 'Freight Code';
MSG_KEY['ITM_FRT_CD'] = 'Freight Code';
MSG_KEY['ITM_FRT_TO'] = 'Freight To';
MSG_KEY['ITM_INV_AMT'] = 'Invoice Amt';
MSG_KEY['ITM_INV_AMT'] = 'Invoice Amt';
MSG_KEY['ITM_INV_AMT'] = 'Invoice Amt';
MSG_KEY['ITM_INV_AMT'] = 'Invoice Amt';
MSG_KEY['ITM_INV_CURR'] = 'Invoice Currency';
MSG_KEY['ITM_INV_CURR'] = 'Invoice Currency';
MSG_KEY['ITM_INV_CURR'] = 'Invoice Currency';
MSG_KEY['ITM_INV_CURR'] = 'Invoice Currency';
MSG_KEY['ITM_INV_EXRT'] = 'Invoice Exchange Rate';
MSG_KEY['ITM_INV_EXRT'] = 'Invoice Exchange Rate';
MSG_KEY['ITM_INV_EXRT'] = 'Invoice Exchange Rate';
MSG_KEY['ITM_INV_EXRT'] = 'Invoice Exchange Rate';
MSG_KEY['ITM_INV_VAT_AMT'] = 'Invoice Vat Amt';
MSG_KEY['ITM_INV_VAT_AMT'] = 'Invoice Vat Amt';
MSG_KEY['ITM_INV_VAT_AMT'] = 'Invoice Vat Amt';
MSG_KEY['ITM_INV_VAT_AMT'] = 'Invoice Vat Amt';
MSG_KEY['ITM_IT_NO'] = 'IT No.';
MSG_KEY['ITM_IT_NO'] = 'IT No.';
MSG_KEY['ITM_LNR_SCAC'] = 'Carrier SCAC';
MSG_KEY['ITM_LNR_SCAC'] = 'Carrier SCAC';
MSG_KEY['ITM_MSG_TP'] = 'Message Type';
MSG_KEY['ITM_MSG_TP'] = 'Message Type';
MSG_KEY['ITM_OFFICE_CD'] = 'Office Code';
MSG_KEY['ITM_OFFICE_NM'] = 'Office Name';
MSG_KEY['ITM_ORD'] = 'Order';
MSG_KEY['ITM_PAYAMOUNT'] = 'Payment Amount';
MSG_KEY['ITM_PAYMENT'] = 'Payment';
MSG_KEY['ITM_PERF_AMT'] = 'Performance Amt';
MSG_KEY['ITM_PERF_AMT'] = 'Performance Amt';
MSG_KEY['ITM_PERF_AMT'] = 'Performance Amt';
MSG_KEY['ITM_PERF_AMT'] = 'Performance Amt';
MSG_KEY['ITM_PERF_CURR'] = 'Performance Currency';
MSG_KEY['ITM_PERF_CURR'] = 'Performance Currency';
MSG_KEY['ITM_PERF_CURR'] = 'Performance Currency';
MSG_KEY['ITM_PERF_CURR'] = 'Performance Currency';
MSG_KEY['ITM_PERF_EXRT'] = 'Performance Exchange Rate';
MSG_KEY['ITM_PERF_EXRT'] = 'Performance Exchange Rate';
MSG_KEY['ITM_PERF_EXRT'] = 'Performance Exchange Rate';
MSG_KEY['ITM_PERF_EXRT'] = 'Performance Exchange Rate';
MSG_KEY['ITM_PERF_VAT_AMT'] = 'Performance Vat Amt';
MSG_KEY['ITM_PERF_VAT_AMT'] = 'Performance Vat Amt';
MSG_KEY['ITM_PERF_VAT_AMT'] = 'Performance Vat Amt';
MSG_KEY['ITM_PERF_VAT_AMT'] = 'Performance Vat Amt';
MSG_KEY['ITM_PERIOD'] = 'Period';
MSG_KEY['ITM_PGM'] = 'Program';
MSG_KEY['ITM_PHN'] = 'Phone';
MSG_KEY['ITM_POR_FL_NM'] = 'POR Full Name';
MSG_KEY['ITM_POR_FL_NM'] = 'POR Full Name';
MSG_KEY['ITM_PRNR'] = 'Partner';
MSG_KEY['ITM_PRNTCD'] = 'Parent Code';
MSG_KEY['ITM_PRT_PATH'] = 'Report File Path';
MSG_KEY['ITM_RATE'] = 'Rate';
MSG_KEY['ITM_RATE'] = 'Rate';
MSG_KEY['ITM_RATE'] = 'Rate';
MSG_KEY['ITM_RATE'] = 'Rate';
MSG_KEY['ITM_Rate_CURR'] = 'Rate Currency';
MSG_KEY['ITM_REFCD'] = 'Reference Code';
MSG_KEY['ITM_RMK'] = 'Remark';
MSG_KEY['ITM_ROLECD'] = 'Role Code';
MSG_KEY['ITM_ROLENM'] = 'Role Name';
MSG_KEY['ITM_SKD'] = 'Schedule';
MSG_KEY['ITM_SNP'] = 'SNP';
MSG_KEY['ITM_SNP'] = 'SNP';
MSG_KEY['ITM_SUBJECT'] = 'Subject';
MSG_KEY['ITM_TARIFF_CURR'] = 'Rate Currency';
MSG_KEY['ITM_TARIFF_CURR'] = 'Rate Currency';
MSG_KEY['ITM_TARIFF_CURR'] = 'Rate Currency';
MSG_KEY['ITM_TRDP_CD'] = 'Customer Code';
MSG_KEY['ITM_TRDP_CD'] = 'Customer Code';
MSG_KEY['ITM_TRDP_CD'] = 'Customer Code';
MSG_KEY['ITM_TRDP_CD'] = 'Customer Code';
MSG_KEY['ITM_UNIT'] = 'Unit';
MSG_KEY['ITM_UNIT'] = 'Unit';
MSG_KEY['ITM_UNIT'] = 'Unit';
MSG_KEY['ITM_UNIT'] = 'Unit';
MSG_KEY['ITM_USRID'] = 'User ID';
MSG_KEY['ITM_USRNMENG'] = 'Name(Eng.)';
MSG_KEY['ITM_USRNMLOCAL'] = 'Local Name';
MSG_KEY['ITM_VAT'] = 'Vat';
MSG_KEY['ITM_VAT'] = 'Vat';
MSG_KEY['ITM_VAT'] = 'Vat';
MSG_KEY['ITM_VAT'] = 'Vat';
MSG_KEY['ITM_VAT_RATE'] = 'Vat Rate';
MSG_KEY['ITM_VAT_RATE'] = 'Vat Rate';
MSG_KEY['ITM_VAT_RATE'] = 'Vat Rate';
MSG_KEY['ITM_VAT_RATE'] = 'Vat Rate';
MSG_KEY['ITM_VOL'] = 'Volume';
MSG_KEY['ITM_VOL'] = 'Volume';
MSG_KEY['ITM_VOL'] = 'Volume';
MSG_KEY['ITM_VOL'] = 'Volume';
MSG_KEY['ITM_XCRT_DT'] = 'Invoice Exchange Date';
MSG_KEY['ITM_XCRT_DT'] = 'Invoice Exchange Date';
MSG_KEY['ITM_XCRT_DT'] = 'Invoice Exchange Date';
MSG_KEY['ITM_XCRT_DT'] = 'Invoice Exchange Date';
MSG_KEY['LGL_ADDR'] = 'Legal Address';
MSG_KEY['LOC_CD'] = 'Location Code';
MSG_KEY['LOCAL_ADDR'] = 'Local Address';
MSG_KEY['LOCAL_NM'] = 'Local Name';
MSG_KEY['MAC_MSG51'] = 'To_Date';
MSG_KEY['MAC_MSG52'] = 'From_Date';
MSG_KEY['MENU_FONT_SIZE'] = 'Menu Font Size';
MSG_KEY['MENU_MIN_WIDTH'] = 'Main Menu Min-Width';
MSG_KEY['MESSAGE'] = 'Message';
MSG_KEY['MONTH'] = 'Month (MM-YYYY)';
MSG_KEY['NAME'] = 'Name';
MSG_KEY['NOD_CD'] = 'Node Code';
MSG_KEY['OFC_CD'] = 'Office Code';
MSG_KEY['PIC'] = 'PIC';
MSG_KEY['PO'] = 'P/O No.';
MSG_KEY['POR_FUL_NM'] = 'POR Full Name';
MSG_KEY['POR_FUL_NM'] = 'POR Full Name';
MSG_KEY['PRNT_LOC_CD'] = 'Parent Location Code';
MSG_KEY['PRNT_OFC'] = 'Parent Office';
MSG_KEY['PTNR'] = 'Partner';
MSG_KEY['REMARK'] = 'Remark';
MSG_KEY['RMK'] = 'Remark';
MSG_KEY['SAL_BRN'] = 'Sales Office';
MSG_KEY['SAL_OFC'] = 'Sales Office';
MSG_KEY['SAL_PRN'] = 'Sales Person';
MSG_KEY['SAVE_BOOKING_ENTRY'] = 'Please save booking entry before create house B/L.';
MSG_KEY['SAVE_CARRIER_BOOKING_ENTRY'] = 'Please save Carrier Booking No before create Master B/L.';
MSG_KEY['SELECT'] = 'Select';
MSG_KEY['SELL_BUY_TP_CD'] = 'Debit/Credit Type';
MSG_KEY['SHT_NM'] = 'Alias';
MSG_KEY['SPLR_CD'] = 'Supplier Code';
MSG_KEY['SPLR_ITEM'] = 'Supplier Item Code';
MSG_KEY['SUB_CONTI_CD'] = 'Sub Continent Code';
MSG_KEY['TEL'] = 'Phone';
MSG_KEY['TGT_AMT'] = 'Target Amount';
MSG_KEY['TIME_TIFF'] = 'Time Tiff';
MSG_KEY['TIT'] = 'Title';
MSG_KEY['TMP_LIST'] = 'Template List';
MSG_KEY['TMP_NAME'] = 'Template List Name';
MSG_KEY['TO_CURR_CD'] = 'To Currency';
MSG_KEY['TRANS_REF_NO'] = 'Trans. Ref. No.';
MSG_KEY['TRDP_CD'] = 'Customer Code';
MSG_KEY['URL'] = 'URL';
MSG_KEY['WH'] = 'Warehouse';
MSG_KEY['XCH_RT_UT'] = 'Exchange Rate';
MSG_KEY['ZIP_CD'] = 'Zip Code';
MSG_KEY['FMS_COM_CFMBLK'] = 'Do you want to Block?';

MSG_KEY['BTN_ROLE_CHECK_MSG'] = 'The same Group ID must be equal and continuous. They cannot have blank Group ID in between them.';
MSG_KEY['BTN_ROLE_CHECK_MSG2'] = 'The "must-be" button can not be groupped.';
MSG_KEY['FMS_COM_CBKG'] = 'Do you want to Create Carrier Booking? ';
MSG_KEY['FMS_COD_SYSBKGNO'] = 'System Bkg. No.';

//#2131 [BINEX V442] NO G/L MAPPING, BUT CAN ISSUE INVOICE USING BILLING CODE
MSG_KEY['FMS_COM_ALT102'] = 'Cannot delete because G/L Code already used!';
MSG_KEY['FMS_COM_ALT103'] = 'There is no G/L Code data!';
MSG_KEY['FMS_COM_ALT104'] = 'Duplicated Booking No. found.';
MSG_KEY['FMS_COM_ALT105'] = 'The Booking No. Information already exists.';
MSG_KEY['FMS_COM_ALT106'] = 'You can assign the number more than 2.';
MSG_KEY['FMS_COM_ALT107'] = 'Spit number should be less than 26';
MSG_KEY['FMS_COM_ALT108'] = 'Container QTY should be less than 30'; //Container Quantity의 수는 30보다 작아야 함
MSG_KEY['FMS_COM_ALT109'] = 'Container number should be less than 50';   //container List의 수는 50보다 작아야 함

MSG_KEY['FMS_COM_ALT110'] = 'Do you want to overwrite the Filing No [ @ ]  ?';

//#2355 [PATENT] B/L Split / Combine
MSG_KEY['FMS_COM_ALT111'] = 'There is some container which are not assigned to B/L.\nDo you want to remove the container from splitted B/Ls. ?';

//#2022
MSG_KEY['FMS_COM_ALT112'] = "Please input 'Title' and 'Contents' field before saving.";

//#1909
MSG_KEY['FMS_COM_ALT113'] = "Cannot delete because Delivery Order has been issued already.";
//#855 [SUNWAY] PREVENT AP CREATION BEFORE AR CREATION 
MSG_KEY['FMS_COM_ALT114'] = ' No A/R has been created for BL @! \n You must create AR Invoice first to create AP. \n To bypass this, please check with Admin with your role control option. ';

//#97  [ZEN] Shipper-Customer 연동 Rule 변경|Customer Assign Rule Enhancement SHIPPER ==>CUSTOMER
MSG_KEY['FMS_COM_CFMCTS'] = 'Do you want to overwrite the Shipper to Customer?\nClick OK to overwrite, Cancel to keep.';
MSG_KEY['FMS_COM_CFMCTC'] = 'Do you want to overwrite the Consignee to Customer?\nClick OK to overwrite, Cancel to keep.';

//#1909 [Premier Cargo] Issues on Inland BL and Inlad Pickup/Delivery
MSG_KEY['FMS_COM_ALT115'] = 'Cannot delete because HB/L was Blocked! '; //HB/L이 blocked 상태이기 때문에 삭제할 수 없습니다!
MSG_KEY['FMS_COM_ALT116'] = 'Cannot delete because MB/L was Blocked! '; //MB/L이 blocked 상태이기 때문에 삭제할 수 없습니다!
MSG_KEY['FMS_COM_ALT117'] = 'Cannot delete because HAWB was Blocked! '; //HAWB이 blocked 상태이기 때문에 삭제할 수 없습니다!
MSG_KEY['FMS_COM_ALT118'] = 'Cannot delete because MAWB was Blocked! '; //MAWB이 blocked 상태이기 때문에 삭제할 수 없습니다!
MSG_KEY['FMS_COM_ALT119'] = 'Please enter Event Date, Event Time, Event Code, Event Name!';

//#476 [unico] Billing Code selection either GNR or Operation Department Validation
MSG_KEY['FMS_COM_ALT120'] = ' Billing Code(s) : ';
MSG_KEY['FMS_COM_ALT121'] = 'No Revenue G/L is assigned, please update before saving.\n- ';
MSG_KEY['FMS_COM_ALT122'] = 'No Cost G/L is assigned, please update before saving.\n- ';
MSG_KEY['FMS_COM_ALT123'] = 'No Debit G/L is assigned, please update before saving.\n- ';
MSG_KEY['FMS_COM_ALT124'] = 'No CR/DB G/L is assigned, please update before saving.\n- ';
MSG_KEY['FMS_COM_ALT125'] = 'No Credit G/L is assigned, please update before saving.\n- ';

//#1276 [LBS] Batch Run 작업 화면 개발
MSG_KEY['FMS_COM_ALT126'] = 'Processing Date must be later than Last processed Year-End Date.';
MSG_KEY['FMS_COM_ALT127'] = 'Check Volume & Profit or G/L.';
MSG_KEY['FMS_COM_ALT128'] =  'Are you sure you want to continue?\n\
This process will batch update all your accounting data ('
MSG_KEY['FMS_COM_ALT129'] =  ') from Processing Date you entered and may cause change(s) to your accounting figures.\n\
	If you have any questions, please consult OPUS Customer Support before proceeding.'
MSG_KEY['FMS_COM_ALT130'] =  'Please set the Processing Date.'
MSG_KEY['FMS_COD_RPTID'] = 'Report ID ';
MSG_KEY['FMS_COD_MRDNM'] = 'MRD Name ';
MSG_KEY['FMS_COD_DELTRSN'] = 'Reason for Deleting ';
//Report Set Management UI
MSG_KEY['FMS_COM_RPT'] = 'Report ID';
MSG_KEY['FMS_COM_RPT_SET'] = 'Report Set';
MSG_KEY['FMS_COM_RPT_CALL_ID'] = 'There is no Call ID data';

MSG_KEY['FMS_COM_ALT131'] = 'Period Max must be greater than or equal to [To – From + 1]'
MSG_KEY['FMS_COM_ALT132'] = 'From Date must be less than To Date'
MSG_KEY['FMS_COM_ALT133'] = 'Please enter Target Date and Period Base before entering the values of From Date, To Date and Period Max'
MSG_KEY['FMS_COM_ALT135'] = 'Target Date or Period Base have not entered yet.'
MSG_KEY['FMS_COM_ALT136'] = 'There is no data to save!'

//Search Condition
MSG_KEY['FMS_COM_ALT132'] = 'Period must be less than or equal to [ @ ] days.'
//#3356 [JTC]HB/L Form 개발
MSG_KEY['FMS_COM_ALT137'] = 'TLI# is missiing. Proceed anyway?';

MSG_KEY['FMS_COM_ALT138'] = '[ @ ] is missing. Please check again!';
MSG_KEY['FMS_COM_ALT139'] = 'G/L root must be created first!';
MSG_KEY['FMS_COM_ALT140'] = 'There is no data to delete!'
MSG_KEY['FMS_COM_ALT141'] = 'There is no G/L Code. Please add G/L first!';
MSG_KEY['FMS_COM_LCL01'] = 'Company / Office Code / Local Name';
MSG_KEY['FMS_COM_GL01'] = 'Code or Name of the GL';

//#3524 Carrier Booking 의 정보로 여러개의 MBL을 생성 시, Carrier Booking# 중복 validation 추가
MSG_KEY['FMS_COM_ALT142'] = 'This Carrier Booking is already assign to another MBL.\nAre you sure to proceed?';

//#3548 OE AMS EDI 화면 보완
MSG_KEY['FMS_COM_ALT143'] = 'Please enter Vessel Nationality.';
MSG_KEY['FMS_COM_ALT144'] = 'Vessel Nationality code should be 2 characters';

MSG_KEY['FMS_COM_ALT145'] = 'Already assign EDI Msg type to Edi config!';
MSG_KEY['FMS_COM_ALT146'] = 'Not found B/L EDI Code at Edi config!';

MSG_KEY['FMS_COM_ALT147'] = 'Already assign B/L EDI CD to another TRDP!';

//#1145[B/L Entry] Validate wrong field name
MSG_KEY['FMS_COM_MARK'] = 'Mark';
MSG_KEY['FMS_COM_INTERNAL_MEMO'] = 'Internal Memory';

//#4035 B/L EDI validation 추가
MSG_KEY['FMS_COM_ALT148'] = 'The B/L is not available for Agent EDI function.';

//#4022 [JAPT] Invoice Currency 가 JPY 인 경우 Local Ex.Rate 정보가 잘못 처리되어 저장된 BUG
MSG_KEY['FMS_COM_ALT149'] = 'Local Ex.Rate will set as 1.0.\nBecause the Currency is Local Currency.';

//#3321 [CLT] 메세지 Description 오류
MSG_KEY['FMS_COM_ALT150'] = 'Please enter the Freight Code before saving.';
MSG_KEY['FMS_COM_ALT151'] = 'Please enter the Rate Currency before saving.';
MSG_KEY['FMS_COM_ALT152'] = 'Please enter the Exchange Currency before saving.';

//#4020 (JAPT) invoice Ex.date, rate validation, amount  추가
MSG_KEY['FMS_COM_ALT153'] = 'Are you sure to change the Total Amount?';
MSG_KEY['FMS_COM_ALT154'] = 'Would you like to change all the Exchange Date and rate?';
MSG_KEY['FMS_COM_ALT155'] = 'Local Ex.Rate will set as 1.0.\nBecause the Currency is Local Currency.';
MSG_KEY['FMS_COM_ALT156'] = 'Would you like to change all the Exchange rate?';
MSG_KEY['FMS_COM_ALT157'] = 'Please input Date information before saving.';
MSG_KEY['FMS_COD_LOADDT'] = 'Load Date';
MSG_KEY['FMS_COD_FINALETA'] = 'Final ETA';

//#4088 [Global Pro] MISC. Operation Entry to have Work Order Button
MSG_KEY['FMS_COM_ALT158'] = 'Create the B/L first.';
//#4931 ** [Korex] After deleting Invoice, you cant cancel inbound& outbound
MSG_KEY['FMS_COM_ALT159'] = 'Closing can be made only to one Billing Customer. Please check Billing Customer.';
//#5241 컨테이너 삭제 시  ITEM List 컨테이너 삭제(동기화 처리)
MSG_KEY['FMS_COM_ALT160'] = 'There is a container in the ITEM list. \n Do you want to Delete?';
MSG_KEY['FMS_COM_ALT161'] = 'You cannot disable this code. It is assigned as default G/L on Master Code > Common > Office Code.';
MSG_KEY['FMS_COM_ALT162'] ='You cannot remove active billing code. If you wish not to use the selected billing code, please uncheck Use column to disable instead.';

//#5686 : [Advanced] Email function contents bug
MSG_KEY['FMS_COM_ALT163'] = 'Do you want to reset the email content?'
	
//#5757 [Binex-LA] Agent EDI 로직 확인 요청
MSG_KEY['FMS_COM_ALT164'] = 'There are multiple Destination Agents, EDI could be sent to single Destination Agent.'	
	
//#5944 [JTC] 메일 전송시 from 주소 변경 요청(default 설정)
MSG_KEY['FMS_COM_ALT165'] = 'Rep. Email is empty. Please enter Rep. Email'
	
//#6827 : [BEST OCEAN] EAWB TRNSMISSION AFTER REVISE DATA
MSG_KEY['FMS_COM_ALT166'] = 'EDI Status is “SENT”, if you wish to resend eAWB EDI, please first check with the Air carrier to see the previous transmission was accepted. If it was not accepted please click "OK" to retransmit eAWB EDI.'	
//#2249 : [SGL US] RECEIVING ERS-18000 FROM EXP/IMP SHIPMENT IN SP MEMO & INVOICE	
MSG_KEY['FMS_COM_ALT167'] = 'Name of images uploaded in Company Logo should not have space characters';
//OFVFOUR-7241 [V4] Delivery time on Trade Partner Entry showing incorrect
MSG_KEY['FMS_COM_ALT168'] = '[Delivery Time] From Time bigger than To Time.'
//#6141 [BNX-TOR] 환율 입력시 중복/누락시 alert messasge
MSG_KEY['FMS_COM_ALT169'] = 'The exchange rate has not it\'s pair. Please check it'
//OFVFOUR-7838: [Miragrown] Date Format on Custom
MSG_KEY['FMS_COM_ALT170'] = 'Please input the date MM/DD/YYYY';