MSG_KEY['EDI_CNFG_HDR1'] = 'DEL||No.|SCAC|TP|URL|Port|ID|PWD|SND_DIR|RCV_DIR|SND_File_REPO|RCV_File_REPO|DESC|SMT_CUST_ID|SNDR_ID|RCVR_ID|RCVR_PWD|VER|IS_Passive|SNDR_PWD|RPT_ID|RPT_PWD|AGT EDI MSG TYPE';
MSG_KEY['MGT_ALT_0010_HDR1'] = '|Del|Use|Alert Type|Office|Name|Type|Event|Email To|Email CC|Parameter|Trade Partner|Trade Partner|( Day +/- )|( Day +/- )|( Day +/- )|( Day +/- )|( Day +/- )|( Day +/- )|Term|Term|Last Sent at|Message|||Created|Created|Modified|Modified|Message Modified|Message Modified';
MSG_KEY['MGT_ALT_0010_HDR2'] = '|Del|Use|Alert Type|Office|Name|Type|Event|Email To|Email CC|Parameter|Target|Group|Starting at|Starting at|Starting at|Ending at|Ending at|Ending at|Time|Send Weekend|Last Sent at|Message|||by|at|by|at|by|at';
MSG_KEY['MGT_ALT_0020_HDR'] = 'Del|No.|Use|Type|Event|Office|Starting at( Time +/- ) |Ending at ( Time +/- )|Term|Contents|CC';
MSG_KEY['MGT_EQS_0010_HDR1'] = '|No.|Country||State Code|Location Code|Location|20 STD|40 STD|40 HQ|RF';
MSG_KEY['MGT_EQS_0010_HDR2'] = '|Del|No.|Country|State Code|Location Code|Location Name';
MSG_KEY['MGT_EQS_0030_HDR1'] = 'Del||Seq|Port|Port|Origin / Destination|ETB|ETD|Transit Time(day)';
MSG_KEY['MGT_EQS_0040_HDR1'] = 'No.|Lane|Origin|Destination|Carrier|Issued by|Issued at|Modified by|Modified at|sel_org_cd|sel_des_cd|lane_nm|f_remark|sel_Frequency_cd';
MSG_KEY['MGT_HIS_0010_HDR1'] = 'Del|STS|Group Name';
MSG_KEY['MGT_HIS_0010_HDR2'] = 'No|Physical Entity Name|Physical Attribute Name|Logical Attribute Name';
MSG_KEY['MGT_HIS_0020_HDR'] = 'DEL||Physical Entity Name|Physical Arribute Name|Logical Attribute Name|Group Name|Key|USE|Warning|Column Description';
MSG_KEY['MGT_HIS_0020_HDR1'] = 'cng_grp_attr_nm|cng_grp_attr_seq';
MSG_KEY['MGT_HIS_0030_HDR'] = 'No.|Group Name|B/L No.|Type|Column|Before|odl_before|After|old_after|Update Date|Office|User ID|C/A No.';
MSG_KEY['MGT_HIS_0040_HDR'] = '|No.||Type|Screen Name|B/L No.|Invoice No.|Other Filing No.|Filing No.|Issued by|Issued at|Email Address & Fax Number|Send Status|Error Message|File||Title|Parameter1|Parameter2|Parameter3';
MSG_KEY['MGT_HOL_0010_HDR1_1'] = 'DEL|No.|ibflag|Apply\nScope|Customer|Customer|From|From|To|To|Exchange\nRate|Day/Month\nType|Apply Date|Apply Date|Issued by|finc_xcrt_seq|Indexing';
MSG_KEY['MGT_HOL_0010_HDR1_2'] = 'DEL|No.|ibflag|Apply\nScope|Code|Name|Currency|Rate Unit|Currency|Rate Unit|Exchange\nRate|Day/Month\nType|From|To|Issued by|finc_xcrt_seq|Indexing';
MSG_KEY['MGT_ITF_0010_HDR'] = '|||Status|Filing No|MB/L No.|Confirmed|D/C Note|D/C Info|MB/L Origin Filing No|MB/L Origin Agent|MB/L Shipper|MB/L Consignee|CHK|Vessel|Voyage|MB/L ETD|MB/L ETA|Post Date|MB/L POR|MB/L POL|MB/L POD|MB/L DEL|Ship Mode|HB/L No.|ETD|ETA|Container|HBL Shipper|HBL Consignee|HBL Notify|HBL POR|HBL POL|HBL POD|HBL DEL|D/L Date|D/L by|Issued Date|Issued by|EDI TP|Office|bl_table_count|mbl_org_agt_cd|mbl_shpr_cd|mbl_cnee_cd|shpr_cd|cnee_cd|ntfy_cd|ref_no|intg_bl_seq|hbl_por_un_loc_cd|hbl_pol_un_loc_cd|hbl_pod_un_loc_cd|hbl_del_un_loc_cd|mbl_por_un_loc_cd|mbl_pol_un_loc_cd|mbl_pod_un_loc_cd|mbl_del_un_loc_cd|mbl_por_un_loc_chk|mbl_pol_un_loc_chk|mbl_pod_un_loc_chk|mbl_del_un_loc_chk|hbl_por_un_loc_chk|hbl_pol_un_loc_chk|hbl_pod_un_loc_chk|hbl_del_un_loc_chk|mbl_map_por_loc_cd|mbl_map_pol_loc_cd|mbl_map_pod_loc_cd|mbl_map_del_loc_cd|hbl_map_por_cd|hbl_map_pol_cd|hbl_map_pod_cd|hbl_map_del_cd|shpr_trdp_addr|shpr_trdp_cnt_cd|cnee_trdp_addr|cnee_trdp_cnt_cd|ntf_trdp_addr|ntf_trdp_cnt_cd|mbl_org_agt_trdp_addr|mbl_org_agt_trdp_cnt_cd|mbl_shpr_trdp_addr|mbl_shpr_trdp_cnt_cd|mbl_cnee_trdp_addr|mbl_cnee_trdp_cnt_cd';
MSG_KEY['MGT_ITF_0020_HDR'] = '||CHK||MB/L No.|Office|Filing No.|ETD|ETA|Container|Shipper|Consignee|Carrier|POL|POD|';
MSG_KEY['MGT_MAC_0010_HDR'] = 'No.||MAC Address|Description|To Date|From Date|Use|';
MSG_KEY['MGT_MAC_0010_HDR1'] = '|No.|User ID|IP Address|Access Time|Status|Description';
MSG_KEY['MGT_MNG_0010_HDR1'] = '|User ID|User Name|Date|Start Time|End Time|Work Time';
MSG_KEY['MGT_OPT_0010_HDR'] = '|DEL|No.|Key|Value|Office|Parameter|Description';
MSG_KEY['MGT_OPT_0011_HDR'] = '|DEL|Configuration Key|Configuration Desc.|Value';
MSG_KEY['MGT_SKD_0010_HDR'] = 'No.|CHK|Block|MB/L No.|HC|Ship Mode|Office|Filing No.|Carrier Bkg. No.|Count|ETD|ETA|ATD|ATA|Container||Triangle Agent||Shipper||Consignee||Billing Carrier|Vessel Name|Voyage||Carrier|HB/L||POR||POL||POD||DEL|AR|AP|DC||Issued by|';
MSG_KEY['MNU_HDR1'] = 'DEL|CHK|No.|STS|Jmenu|Menu|Order|English|Chinese|Japanese|Korean|Description|Using|Used Count';
MSG_KEY['MNU_SUB_POPUP_HDR'] = 'MNU_SEQ|CHK|TOP MENU NAME|PRNT_MNU_SEQ|STS';
MSG_KEY['MSG_LNG_HDR1'] = '|DEL|No.|MSG KEY SEQ|MSG Prop. Type|MSG File|LANG|MSG Key|MSG Value|Description|Modi. Date';
MSG_KEY['NEW_ROLE_BTN_HDR'] = 'Top Menu|Sub Menu|Pgm Menu';
MSG_KEY['PGM_BTN_HDR1'] = 'DEL|No.|STS|Program|URL|Order|English|Using';
MSG_KEY['PGM_BTN_ROLE_HDR1'] = 'DEL|ID|Key|Position|Order|Must be|Style|Group|Using|Display|Description|Link Paramter|Action';
MSG_KEY['PGM_HDR1'] = 'DEL|CHK|Button|STS|Program|Program ID|URL|Order|English|Chinese|Japanese|Korean|Description|Using|Used Count';
MSG_KEY['PGM_POP_HDR1'] = '|No.|ID|Program|URL|Description';
MSG_KEY['PGM_SUB_POPUP_HDR'] = 'Master Menu|MNU_SEQ|CHK|Sub Menu|PRNT_MNU_SEQ|STS';
MSG_KEY['PROP_CREATE_HDR1'] = '|DEL|No.|MSG PROP TYPE|MSG File|MSG File Name|LANG|Modi. Date|CHK';
MSG_KEY['ROLE_BTN_HDR1_1'] = '||Top Menu|CHK||Sub Menu|CHK||Pgm Menu|CHK|Button|Button|Button|Button|Button|Button|Button|Button|Button|';
MSG_KEY['ROLE_BTN_HDR1_2'] = '||Top Menu|CHK||Sub Menu|CHK||Pgm Menu|CHK|Retrieve|New|Save|Delete|Print|Excel|7|8|9|Extension|';
MSG_KEY['ROLE_HDR1'] = 'DEL|STS|Role Code|Role Name|Order|Description|Target Auth Role|Use Y/N';
MSG_KEY['SUBCD_HDR1'] = 'Status|DEL|Code|Name|Code Order|Use Y/N|Remark';
MSG_KEY['TOMCD_HDR1'] = 'Status|DEL|Code|Name|Parent Code|Reference Code|Code Length|Code Type|Use Y/N|Remark';
MSG_KEY['TOP_MNU_HDR1'] = 'DEL|No.|STS|Menu|Order|English|Chinese|Japanese|Korean|Description|Using|Count|Index';
MSG_KEY['USERMGMT_HDR1'] = 'Status|User ID|Name|Local Name|Language|Office|Office|Department|Team|Role|Address|EMail|Phone No. |Fax No.|SNS ID|Status|Default Contract|Default Contract|Warehouse Config|Default Warehouse|Outboud Order Type|Passwd Reset|Office Code';
MSG_KEY['USERMGMT_HDR2'] = '|No.|User ID|IP Address|Type|Access Time';
MSG_KEY['USERMGMT_HDR3'] = '|DEL|No.|IP SEQ|IP Address|From|To|User|Modified by|Modified Office|Modified Time|Use Y/N';
MSG_KEY['USERMGMT_HDR4'] = 'DEL|STS|Screen|Type Report|Content Email|Type Email|USE Y/N|Remark|ScreenOld|Type Report Old';
MSG_KEY['USERORDERBY_GRANT_HDR'] = '|Menu|Order By 1|Order By 2|Order By 3|Order By 4';
MSG_KEY['SYS_COD_CONT'] = 'Contents'; //게시 내용
MSG_KEY['SYS_COD_EXDT'] = 'Expire Date'; //만료일
MSG_KEY['SYS_COD_MENU'] = 'Menu'; //메뉴
MSG_KEY['SYS_COD_TITL'] = 'Title'; //제목
MSG_KEY['SYS_COM_ALT002'] = 'Please change the name of selected File! \nFile Name cannot exceed 40 characters including the Extension. '; //선택한 파일의 파일명을 변경해 주세요! 확장자를 포함한 전체 파일명은 40자를 초과할 수 없습니다.
MSG_KEY['SYS_COM_ALT003'] = 'You must have the authority to this function. Please check authorization grant to your username!'; //이 기능에는 권한이 부여되어 있습니다. 부여된 권한을 먼저 취소해 주세요!
MSG_KEY['SYS_COM_ALT004'] = 'Please Delete Sub-Menu first!'; //Sub-Menu를 먼저 삭제해 주세요!
MSG_KEY['SYS_COM_ALT005'] = 'This role was used at User Information. Please change User Information!'; //사용자 정보에서 사용 중인 Role입니다. 사용자 정보를 변경해 주세요!
MSG_KEY['SYS_COM_ALT006'] = 'This role was used at Role/Screen Mapping. Please change Role/Screen Mapping!';
MSG_KEY['SYS_COM_ALT007'] = 'This code was already used. Please check the Code again!'; //사용 중인 코드입니다. 코드를 확인해 주세요!
MSG_KEY['SYS_COM_ALT008'] = 'The End date is greater than the Start date.';
MSG_KEY['SYS_COM_ALT009'] = 'Duplicated data.';
MSG_KEY['SYS_COM_ALT010'] = 'Please check the date format.';

MSG_KEY['RPTMNG_HDR'] = 'DEL|STS|Mrd Key|Mrd|Path|Letter|A4 EN|A4 ZH|A4 JA|Program|Description';
MSG_KEY['PGM_CFG_MNG_HDR1'] = 'DEL||Office|Program ID|Program Name|Target\nDate Type|Period Base|From Date|To Date|Period Max|Use \nInitial Setting|Initial \nData Load|Rows\non Page|Reset\nIBSheet Head Info\nY/N|IBSheet Header Info.\n(sheetid:-:col,-,sheetid:-:col)|Use Detail Setting\nY/N|Detail Setting|Created Time|Modified Time';
MSG_KEY['NWRPTMNG_HDR'] = '|No.|STS|Module|Report ID|Report Name|Call ID|Purpose|MRD Name|MRD Path|Paper|Language|Is Check|Is for a company|Remark|Query|PDF Name|Reason for Deleting';

MSG_KEY['MGT_ITF_0010_HDR2_1'] = 'B/L No.|Freight\nCode|Mapping Freight\nCode|Freight\nName|D/C|P/C|Unit|TP/SZ|Rate\nCurr.|Rate|Volume|Amount|Debit/Credit|Debit/Credit|Debit/Credit|Debit/Credit|Debit/Credit|Debit/Credit|bl_seq|frt_list_seq|biz_clss_cd|IBFlag';
MSG_KEY['MGT_ITF_0010_HDR2_2'] = 'B/L No.|Freight\nCode|Mapping Freight\nCode|Freight\nName|D/C|P/C|Unit|TP/SZ|Rate\nCurr.|Rate|Volume|Amount|Curr.|Ex. Date|Ex. Rate|Revenue/Cost|Debit|Credit|bl_seq|frt_list_seq|biz_clss_cd|IBFlag';
MSG_KEY['SYS_COM_ALT011'] = 'Please check D/C Mapping Freight Code.';
MSG_KEY['SYS_COM_ALT012'] = 'Please input Post Date.';
MSG_KEY['SYS_COM_ALT014'] = 'Please check Ship Mode.';
// OFVFOUR-7503 [SOUTH EAST WORLD WIDE] OI B/L EDI DATA & OFFICE CODE PREFIX
MSG_KEY['SYS_COM_ALT015'] = 'Missing Delivery ETA \nFilling no. is generated by Delivery ETA.';