MSG_KEY['SEE_FRT_0010_HDR1'] = 'TP/SZ|Qty';
MSG_KEY['SEE_FRT_0010_HDR2_1'] = 'DEL||CHK|Selling/\nDebit|Freight\nCode|Freight\nCode|Customer Code|Customer Code|Rate\nCurr.|Unit|TP/SZ|Vol.|Inc.|P/C|Rate|Qty|Vat|Vat|Amount(Invoice)|Amount(Invoice)|Amount(Invoice)|Amount(Invoice)|Amount(Invoice)|Amount(Invoice)|Amount(Performance)|Amount(Performance)|Amount(Performance)|Amount(Performance)|Invoice No.|Status Code|Status|Dept.|Issued by|Auto Rate FLAG|Rate No.|Item No.|IBFlag';
MSG_KEY['SEE_FRT_0010_HDR2_2'] = 'DEL||CHK|Selling/\nDebit|Freight\nCode|Name|Code|Name|Rate\nCurr.|Unit|TP/SZ|Vol.|Inc.|P/C|Rate|Qty|%|Rate|Curr.|Ex. Rate|Ex. Date|Amount|Vat|Total Amount|Curr.|Ex. Rate|Amount|Vat|Invoice No.|Status Code|Status|Dept.|Issued by|Auto Rate FLAG|Rate No.|Item No..|IBFlag';
MSG_KEY['SEE_FRT_0010_HDR3'] = 'Rate Curr.|Ex. Rate|Amount|Inv. Amount|';
MSG_KEY['SEE_FRT_0010_HDR4_1'] = 'DEL||CHK|Buying/\nCredit|Freight\nCode|Freight\nCode|Customer Code|Customer Code|Rate\nCurr.|Unit|TP/SZ|Vol.|Inc.|P/C|Rate|Qty|Vat|Vat|Amount(Invoice)|Amount(Invoice)|Amount(Invoice)|Amount(Invoice)|Amount(Invoice)|Amount(Invoice)|Amount(Performance)|Amount(Performance)|Amount(Performance)|Amount(Performance)|Invoice No.|Status Code|Status|Dept.|Issued by|Auto Rate FLAG|Rate No.|Item No.|IBFlag';
MSG_KEY['SEE_FRT_0010_HDR4_2'] = 'DEL||CHK|Buying/\nCredit|Freight\nCode|Name|Code|Name|Rate\nCurr.|Unit|TP/SZ|Vol.|Inc.|P/C|Rate|Qty|%|Rate|Curr.|Ex. Rate|Ex. Date|Amount|Vat|Total Amount|Curr.|Ex. Rate|Amount|Vat|Invoice No.|Status Code|Status|Dept.|Issued by|Auto Rate FLAG|Rate No.|Item No.|IBFlag';
MSG_KEY['SEE_FRT_0010_HDR5_1'] = 'No.|HB/L No.|Shipper|Consignee|Partner|POR|POL|POD|DEL|Weight|Measure|Amount(Performance)|Amount(Performance)|';
MSG_KEY['SEE_FRT_0010_HDR5_2'] = 'No.|HB/L No.|Shipper|Consignee|Partner|POR|POL|POD|DEL|Weight|Measure|Selling|Buying|';
MSG_KEY['COM_FRT_ALT001'] = 'Selected trade partner has the [Cash On Delivery] status. Do you want to proceed?'; //COD(Cash On Delivery) 입니다!
MSG_KEY['COM_FRT_ALT002'] = 'Please enter a correct value! - Hour: Between 0 ~ 23'; //시간을 정확히 입력해 주세요!
MSG_KEY['COM_FRT_ALT003'] = 'Please enter a correct value! - Minute: Between 0 ~ 59'; //분을 정확히 입력해 주세요!
MSG_KEY['COM_FRT_ALT004'] = 'You have to create S/R or MAWB first!';
MSG_KEY['COM_FRT_ALT005'] = 'The Currency is different. Please check the Invoice Exchange Rate!';
MSG_KEY['COM_FRT_ALT006'] = 'It is only possible to use Two Currencies. Please check the Rate Currency!';
MSG_KEY['COM_FRT_ALT007'] = 'You can only select the same Selling and Buying!';
MSG_KEY['COM_FRT_ALT008'] = 'You can only select the same Trade Partner!';
MSG_KEY['COM_FRT_ALT009'] = 'Selected Type/Size is already in use. Please select another Type/Size!';
MSG_KEY['COM_FRT_ALT010'] = 'Container Quantity is not matched.\nDo you want to proceed?';
MSG_KEY['COM_FRT_ALT011'] = 'Invoice Currency is KRW. Please round up or down!';
MSG_KEY['COM_FRT_ALT011'] = 'Invoice Currency is KRW. Please round up or down!';
MSG_KEY['COM_FRT_ALT012'] = 'You can only select Container Unit!';
MSG_KEY['COM_FRT_ALT013'] = 'You can only select the same Currency.!';
MSG_KEY['COM_FRT_ALT014'] = 'Annual Bond No : @ \nExpiration Date : @';
MSG_KEY['COM_FRT_ALT015'] = 'Selected trade partner has the [Black List] Status. Do not use the trade partner!';
MSG_KEY['COM_FRT_CFM001'] = 'You cannot modify the Data after Confirmation! Would you like to continue?';
MSG_KEY['COM_FRT_CFM002'] = 'Former Data will be deleted! Do you want to Auto-Generate Freight?';
MSG_KEY['COM_FRT_CFM003'] = 'You can check after [SAVE].';
MSG_KEY['COM_FRT_CFM004'] = 'The amount of some items is 0. Delete these items?';
MSG_KEY['COM_FRT_CFM005'] = 'Selected trade partner is on [Credit Hold] status. Do you want to proceed?';
MSG_KEY['COM_FRT_CFM006'] = 'Selected trade partner has the [Over Credit Limit] status. The over credit is $@. Do you want to proceed?';
MSG_KEY['COM_FRT_CFM007'] = 'Selected trade partner has the [Over Due] status. Current balance amount is overdue. Do you want to proceed?';
MSG_KEY['COM_FRT_CFM008'] = 'Selected trade partner has the [Over Due & Over Credit Limit] status. The over credit is $@. Do you want to proceed?';
MSG_KEY['COM_FRT_CFM009'] = "Selected trade partner has exceeded its credit limit.\nYou are not authorized to issue any document(s) when credit limit is exceeded.\nPlease update trade partner's credit limit or have an authorized user/admin issue the document(s).";
MSG_KEY['COM_FRT_CFM010'] = "Unable to save! Due to Trade Partner exceeding Credit Limit.\nPlease update Trade Partner's credit limit or enable issue document for this screen.";
/*OFVFOUR-7919 [BNX-TOR] Question for total profit amount*/
MSG_KEY['COM_FRT_CFM011'] = "Please enter a Mandatory Value! - Sale Type";
MSG_KEY['COM_WHR_CFM004'] = 'The B/L Information already exists. \nClick YES to overwrite current Shipper, Consignee, Vendor, Customer, P/O No. \nor Click CANCEL to keep Shipper, Consignee, but retrieve Dimension information.';
MSG_KEY['COM_WHR_CFM005'] = 'The B/L Information already exists. \nClick YES to overwrite current Shipper, Consignee, Customer, P/O No. \nor Click CANCEL to keep Shipper, Consignee, but retrieve Dimension information.';
MSG_KEY['COM_WHR_CFM006'] = '[AR Bill To] in Account Receivable is not the same as the Customer code, Arrival Notice will not show the freight.';
//OFVFOUR-7911 [AIF] MANAGING/ALERT CUSTOMER'S OUTSTANDING (OVERDUE)
MSG_KEY['COM_FRT_CFM012'] = 'Customer @ has the overdue amount of $@. Do you want to proceed?';