MSG_KEY['ACC_INV_0010_HDR'] = '|CHK|No.|Billing Code|Name|Currency|Rate|Qty|Ex. Rate|Amount|VAT Rate|VAT Amount|Total Amount';
MSG_KEY['ACC_INV_0010_HDR2'] = 'CHK|No.|STS|HB/L No.|MB/L No.|Booking No.|Work Order No.|Freight Code|Freight Name|Rate\nCurrency|Invoice\nCurrency|Rate|Qty|Ex. Rate|Amount|VAT.Rate|VAT Amount|TOT Amount|FRT_SEQ|TRDP_CD|INV_ISS_FLG|INTG_B/L_SEQ|INV_NO|FRT_ASK_CLSS_CD|RLT_CNT|INV_SEQ|AIRSEA|BND';
MSG_KEY['ACC_INV_0010_HDR2_1'] = 'DEL||CHK|Freight\nCode|Freight\nName|trdp_cd|trdp_nm|P/C|Unit|TP/SZ|VAT|VAT|VAT|VAT|VAT|VAT|VAT|VAT|Rate|Volume|Amount|Currency|Ex. Rate|Ex. Date|Account Receivable|Account Receivable|Account Receivable|inv_seq|intg_bl_seq|inv_no|tax_flg|IBFlag';
MSG_KEY['ACC_INV_0010_HDR2_2'] = 'DEL||CHK|Freight\nCode|Freight\nName|trdp_cd|trdp_nm|P/C|Unit|TP/SZ|%|VAT Code|%(1)|VAT Code(1)|%(2)|VAT Code(2)|%(-)|Rate|Rate|Volume|Amount|Currency|Ex. Rate|Ex. Date|Amount|VAT|Total Amount|tax_flg|IBFlag';
MSG_KEY['ACC_INV_0010_HDR2_3'] = 'DEL||CHK|Freight\nCode|Freight\nName|trdp_cd|trdp_nm|P/C|Unit|TP/SZ|Rate\nCurr.|VAT|VAT|VAT|VAT|VAT|VAT|VAT|VAT|Rate|Volume|Amount|Account Receivable|Account Receivable|Account Receivable|Account Receivable|Account Receivable|Account Receivable|Account Receivable|inv_seq|intg_bl_seq|inv_no|tax_flg|IBFlag';
MSG_KEY['ACC_INV_0010_HDR2_4'] = 'DEL||CHK|Freight\nCode|Freight\nName|trdp_cd|trdp_nm|P/C|Unit|TP/SZ|Rate\nCurr.|%|VAT Code|%(1)|VAT Code(1)|%(2)|VAT Code(2)|%(-)|Rate|Rate|Volume|Amount|Curr.|Ex. Date|Ex. Rate|Amount|VAT|Total Amount|tax_flg|IBFlag';
MSG_KEY['ACC_INV_0020_HDR'] = 'CHK|ibflag|No.|Billing Date|ETD/ETA|Due Date|Customer|MB/L No.|HB/L No.|Invoice No.|Curr.|Invoice Amount|Settle Amount|Balance Amount|Local Amount|Buying Inv No.|Status|Collection\nComplete|Invoice\nPrint|Invoice\nCancel|Create\nType|Slip No.|Ex. Date|Settle Date|Dept/User';
MSG_KEY['ACC_INV_0020_HDR2_1'] = 'DEL||CHK|B/L No.|Freight\nCode|Freight\nName|trdp_cd|trdp_nm|D/C|P/C|Unit|TP/SZ|Rate|Volume|Agent Rate|Qty|Currency|Ex. Rate|Ex. Date|Debit/Credit|Debit/Credit|Debit/Credit|Debit/Credit|Debit/Credit|Debit/Credit|Profit/Share|inv_seq|intg_bl_seq|inv_no|IBFlag';
MSG_KEY['ACC_INV_0020_HDR2_2'] = 'DEL||CHK|B/L No.|Freight\nCode|Freight\nName|trdp_cd|trdp_nm|D/C|P/C|Unit|TP/SZ|Rate|Volume|Agent Rate|Qty|Currency|Ex. Rate|Ex. Date|Amount|VAT|Total Amount|Revenue/Cost|Debit|Credit|Profit/Share|inv_seq|intg_bl_seq|inv_no|IBFlag';
MSG_KEY['ACC_INV_0020_HDR2_3'] = 'DEL||CHK|B/L No.|Freight\nCode|Freight\nName|trdp_cd|trdp_nm|D/C|P/C|Unit|TP/SZ|Rate\nCurr.|Rate|Volume|Agent Rate|Amount|Debit/Credit|Debit/Credit|Debit/Credit|Debit/Credit|Debit/Credit|Debit/Credit|Debit/Credit|Debit/Credit|Debit/Credit|Profit/Share|inv_seq|intg_bl_seq|inv_no|IBFlag';
MSG_KEY['ACC_INV_0020_HDR2_4'] = 'DEL||CHK|B/L No.|Freight\nCode|Freight\nName|trdp_cd|trdp_nm|D/C|P/C|Unit|TP/SZ|Rate\nCurr.|Rate|Volume|Agent Rate|Amount|Curr.|Ex. Date|Ex. Rate|Amount|VAT|Total Amount|Revenue/Cost|Debit|Credit|Profit/Share|inv_seq|intg_bl_seq|inv_no|IBFlag';
MSG_KEY['ACC_INV_0021_HDR'] = 'CHK|ibflag|No.|Invoice No.|Invoice Sub\nSequence|Invoice Amount|Rcvd|Balance|Creation By|Creation Date';
MSG_KEY['ACC_INV_0030_HDR_1'] = 'DEL||CHK|Freight\nCode|Freight\nName|trdp_cd|trdp_nm|P/C|Unit|TP/SZ|VAT|VAT|VAT|VAT|VAT|VAT|VAT|VAT|Rate|Volume|Amount|Currency|Ex. Rate|Ex. Date|Account Payable|Account Payable|Account Payable|inv_seq|intg_bl_seq|inv_no|tax_flg|IBFlag';
MSG_KEY['ACC_INV_0030_HDR_2'] = 'DEL||CHK|Freight\nCode|Freight\nName|trdp_cd|trdp_nm|P/C|Unit|TP/SZ|%|VAT Code|%(1)|VAT Code(1)|%(2)|VAT Code(2)|%(-)|Rate|Rate|Volume|Amount|Currency|Ex. Rate|Ex. Date|Amount|VAT|Total Amount|tax_flg|tax_flg|IBFlag';
MSG_KEY['ACC_INV_0030_HDR_3'] = 'DEL||CHK|Freight\nCode|Freight\nName|trdp_cd|trdp_nm|P/C|Unit|TP/SZ|Rate\nCurr.|VAT|VAT|VAT|VAT|VAT|VAT|VAT|VAT|Rate|Volume|Amount|Account Payable|Account Payable|Account Payable|Account Payable|Account Payable|Account Payable|inv_seq|intg_bl_seq|inv_no|tax_flg|IBFlag';
MSG_KEY['ACC_INV_0030_HDR_4'] = 'DEL||CHK|Freight\nCode|Freight\nName|trdp_cd|trdp_nm|P/C|Unit|TP/SZ|Rate\nCurr.|%|VAT Code|%(1)|VAT Code(1)|%(2)|VAT Code(2)|%(-)|Rate|Rate|Volume|Amount|Curr.|Ex. Date|Ex. Rate|Amount|VAT|Total Amount|tax_flg|IBFlag';
MSG_KEY['ACC_INV_0030_HDR1'] = 'CHK|No.|STS|Customer|HB/L No.|MB/L No.|Booking No.|Work Order No.|POL|POD|ETD|ETA|Package|Weight|Measurement|INTG_BL_SEQ|INV_SEQ|TRDP_CD|FINC_OFC|AIRSEA|BND';
MSG_KEY['ACC_INV_0030_HDR2_1'] = 'CHK|No.|STS|HB/L No.|MB/L No.|Booking No.|Work Order No.|Freight Code|Freight Name|Currency|Debit|Debit|Debit|Debit|Credit|Credit|Credit|Credit|FRT_SEQ|TRDP_CD|INV_ISS_FLG|INTG_BL_SEQ|INV_No.|FRT_ASK_CLSS_CD|RLT_CNT|INV_SEQ|SELL_BUY|AIRSEA|BND';
MSG_KEY['ACC_INV_0030_HDR2_2'] = 'CHK|No.|STS|HB/L No.|MB/L No.|Booking No.|Work Order No.|Freight Code|Freight Name|Currency|Rate|Qty|Ex. Rate|Amount|Rate|Qty|Ex. Rate|Amount|FRT_SEQ|TRDP_CD|INV_ISS_FLG|INTG_BL_SEQ|INV_No.|FRT_ASK_CLSS_CD|RLT_CNT|INV_SEQ|SELL_BUY|AIRSEA|BND';
MSG_KEY['ACC_INV_0031_HDR_1'] = 'DEL||CHK|Billing Code|Description|Office|trdp_cd|trdp_nm|P/C|Unit|TP/SZ|VAT|VAT|VAT|VAT|VAT|VAT|VAT|VAT|Rate|Volume|Amount|Currency|Ex. Rate|Ex. Date|Amount|Total Amount|inv_seq|intg_bl_seq|inv_no|tax_flg|IBFlag';
MSG_KEY['ACC_INV_0031_HDR_2'] = 'DEL||CHK|Billing Code|Description|Office|trdp_cd|trdp_nm|P/C|Unit|TP/SZ|%|VAT Code|%(1)|VAT Code(1)|%(2)|VAT Code(2)|Rt|Rate|Rate|Volume|Amount|Currency|Ex. Rate|Ex. Date|Amount|Total Amount|tax_flg|IBFlag';
MSG_KEY['ACC_INV_0032_HDR1'] = 'Block|CHK|Type|Post Date|Invoice Date|Due Date||Invoice No.|Invoice No.|Customer/Vendor|NET Amount|NET Amount|NET Amount|VAT Amount|Invoice Amount|Paid Amount|L.Paid\nDate|Last Chk No.|Balance|Over\nDue|Office|Currency|Issued by|Create Time|Last Modified by||Last Modify Time|Remark';
MSG_KEY['ACC_INV_0032_HDR1_2'] = 'Block|CHK|Type|Post Date|Invoice Date|Due Date||Invoice No.|Invoice No.|Customer/Vendor|Duty & Tax|Non-Taxable Amount|Taxable Amount|VAT Amount|Invoice Amount|Paid Amount|L.Paid\nDate|Last Chk No.|Balance|Over\nDue|Office|Currency|Issued by|Create Time|Last Modified by||Last Modify Time|Remark';
MSG_KEY['ACC_INV_0032_HDR2'] = 'Block|CHK|Type|Post Date|Invoice Date|Due Date|Department|Invoice No.|Invoice No.|Customer/Vendor|NET Amount|NET Amount|NET Amount|VAT Amount|WHD Amount|Invoice Amount|Paid Amount|L.Paid\nDate|Last Chk No.|Balance|Over\nDue|Office|Currency|Issued by|Create Time|Last Modified by||Last Modify Time|Remark';
MSG_KEY['ACC_INV_0032_HDR2_2'] = 'Block|CHK|Type|Post Date|Invoice Date|Due Date|Department|Invoice No.|Invoice No.|Customer/Vendor|Duty & Tax|Non-Taxable Amount|Taxable Amount|VAT Amount|WHD Amount|Invoice Amount|Paid Amount|L.Paid\nDate|Last Chk No.|Balance|Over\nDue|Office|Currency|Issued by|Create Time|Last Modified by||Last Modify Time|Remark';
MSG_KEY['ACC_INV_0033_HDR_1'] = 'DEL||CHK|Billing Code|Description|trdp_cd|trdp_nm|P/C|Unit|TP/SZ|Volume|Rate|Amount|Currency|Ex. Rate|Ex. Date|Amount|VAT|VAT|VAT|Total Amount||||||||||||||Balance Amount|inv_seq|intg_bl_seq|inv_no|ref_eng_ofc_nm|IBFlag';
MSG_KEY['ACC_INV_0033_HDR_2'] = 'DEL||CHK|Billing Code|Description|trdp_cd|trdp_nm|P/C|Unit|TP/SZ|Volume|Rate|Amount|Currency|Ex. Rate|Ex. Date|Amount|%|Rt|Rate|Total Amount||||||||||||||Balance Amount|IBFlag';
MSG_KEY['ACC_INV_0034_HDR'] = 'CHK|Type|Post Date|Vendor\nInvoice No.|Invoice No.|Vendor|Invoice Amount|Paid Amount|Balance|Over\nDue|Office|Currency|Issued by|Create Time|Last Modified by|Last Mofify Time';
MSG_KEY['ACC_INV_0035_HDR_1'] = 'DEL||CHK|Billing Code|Description|Office|trdp_cd|trdp_nm|P/C|Unit|TP/SZ|VAT|VAT|VAT|VAT|VAT|VAT|VAT|VAT|Rate|Volume|Amount|Currency|Ex. Rate|Ex. Date|Amount|Total Amount|inv_seq|intg_bl_seq|inv_no|tax_flg|IBFlag';
MSG_KEY['ACC_INV_0035_HDR_2'] = 'DEL||CHK|Billing Code|Description|Office|trdp_cd|trdp_nm|P/C|Unit|TP/SZ|%|VAT Code|%(1)|VAT Code(1)|%(2)|VAT Code(2)|Rt|Rate|Rate|Volume|Amount|Currency|Ex. Rate|Ex. Date|Amount|Total Amount|tax_flg|IBFlag';
//OFVFOUR-8038: [BNX-TOR] Adding Rlsd.Date column into AR/AP list
MSG_KEY['ACC_INV_0040_HDR1'] =  'Block|CHK|Type|Post Date|Invoice Date|Due Date|Invoice No.|Bill To|Tax ID No.|Currency|NET Amount|NET Amount|NET Amount|VAT Amount|WHD Amount|Invoice Amount|Paid Amount|L.Paid\nDate|Last Chk No.|Tax Invoice No.|Tax Bill|Org Tax Invoice No.|Org Tax Bill|Financial Office|Balance|HB/L No.|Released Date|Over\nDue|MB/L No.|Filing No.|Other Filing No.|WMS SEQ.|Warehouse Filing No.|Agent Ref. No.|Cust Ref. No.|Vendor\nInvoice No.|Ship To|Office|Remark|POL|ETD|POD|ETA|Issued by|Created Time|Last Modified by||Last Modified Time|TP Code|Alias|Local Amount|Voucher Type|Voucher No.|Bank Date|||||||||||||||||||||||||||||';
MSG_KEY['ACC_INV_0040_HDR2'] =  'Block|CHK|Type|Post Date|Invoice Date|Due Date|Invoice No.|Bill To|Tax ID No.|Currency|Duty & Tax|Non-Taxable Amount|Taxable Amount|VAT Amount|WHD Amount|Invoice Amount|Paid Amount|L.Paid\nDate|Last Chk No.|Tax Invoice No.|Tax Bill|Org Tax Invoice No.|Org Tax Bill|Financial Office|Balance|HB/L No.|Released Date|Over\nDue|MB/L No.|Filing No.|Other Filing No.|WMS SEQ.|Warehouse Filing No.|Agent Ref. No.|Cust Ref. No.|Vendor\nInvoice No.|Ship To|Office|Remark|POL|ETD|POD|ETA|Issued by|Created Time|Last Modified by||Last Modified Time|TP Code|Alias|Local Amount|Voucher Type|Voucher No.|Bank Date|||||||||||||||||||||||||||||';
MSG_KEY['ACC_INV_0050_HDR1'] = '|No.|Bound|ETD/ETA|HB/L|CNTR Type & Qty|Team|User|Customer|POL|POD|DEL|USD|USD|USD|Local|Local|Local';
MSG_KEY['ACC_INV_0050_HDR2'] = '|No.|Bound|ETD/ETA|HB/L|CNTR Type & Qty|Team|User|Customer|POL|POD|DEL|Revenue|Cost|Profit|Revenue|Cost|Profit';
MSG_KEY['ACC_INV_0051_HDR'] = 'inv_seq|inv_tp|inv_no|intg_bl_seq|oth_seq|bl_cnt|bl_ofc|trdp_cd';
MSG_KEY['ACC_INV_0060_HDR1_1'] = '|Team/Bound|Team/Bound|USD|USD|USD|USD|Local|Local|Local|Local|Cargo Type & Qty|Cargo Type & Qty|Cargo Type & Qty|Cargo Type & Qty|Cargo Type & Qty|Cargo Type & Qty|Cargo Type & Qty|Cargo Type & Qty|Cargo Type & Qty|Cargo Type & Qty';
MSG_KEY['ACC_INV_0060_HDR1_2'] = '|Team/Bound|Team/Bound|Revenue|Cost|Profit|Ratio|Revenue|Cost|Profit|Ratio|20|20|40|40|40HC|40HC|Total Unit|TEU|LCL(MEAS)|Bulk(G.W)';
MSG_KEY['ACC_INV_0060_HDR2_1'] = '|Team/Bound|Team/Bound|USD|USD|USD|USD|Local|Local|Local|Local|Qty & Wgt|Qty & Wgt|Qty & Wgt|Qty & Wgt|Qty & Wgt';
MSG_KEY['ACC_INV_0060_HDR2_2'] = '|Team/Bound|Team/Bound|Revenue|Cost|Profit|Ratio|Revenue|Cost|Profit|Ratio|PKG|PKG|G.Weight|G.Weight|C.Weight|C.Weight';
MSG_KEY['ACC_INV_0070_HDR1'] = '|Partner|Bound|Department|Currency|Balance|Debit|Credit';
MSG_KEY['ACC_INV_0070_HDR2'] = '|No.|ETD/ETA|Due Date|MB/L|HB/L|Invoice No.|Filing No.|Currency|Debit|Collection|Credit|Disbursement';
MSG_KEY['ACC_INV_0080_HDR1'] = '|No.|Client|Client|B/L No.|Schedule|Schedule|Schedule|Schedule|Shpr|Cnee|POL|POD|Style No./File No.|Vessel/Flight|Cargo Detail|Cargo Detail|Cargo Detail|Cargo Detail|Cargo Detail|Cargo Detail|Material Quantity';
MSG_KEY['ACC_INV_0080_HDR1_1'] = 'Status|INTG B/L|Bkg. No.|HB/L No.|Status|Status Label';
MSG_KEY['ACC_INV_0080_HDR2'] = "|No.|Dept|Name|B/L No.|ETD|ETA|ATA|D/O|Shpr|Cnee|POL|POD|Style No./File No.|Vessel/Flight|20\'|40\'|LCL|Air|Weight|CBM|Material Quantity";
MSG_KEY['ACC_INV_0080_HDR2_1'] = 'DEL|Invoice No.|Filing No.|Post Date|ETD/ETA|HB/L No.| MB/L No.|Foreign|Foreign|Local|dept_nm|Currency|Invoice Amount|VAT|Total Amount|inv_seq|Office';
MSG_KEY['ACC_INV_0080_HDR2_2'] = 'DEL|Invoice No.|Filing No.|Billing Date|ETD/ETA|HB/L No.| MB/L No.|Currency|Sum Amount |Sum Amount|Total Amount|Dept/User';
MSG_KEY['ACC_INV_0080_HDR3_1'] = 'Currency|Invoice Amount|VAT|Total Amount|IBFlag';
MSG_KEY['ACC_INV_0081_HDR1'] = 'CHK|Invoice No.|Customer|Customer|Foreign Currency|Foreign Amount|Local Amount|Currrency|Amount|VAT|SUM AMT|HB/L No.|MB/L No.|Dept.|P.I.C|';
MSG_KEY['ACC_INV_0081_HDR2'] = 'CHK|Invoice No.|Customer|Customer|Foreign Currency|Foreign Amount|Local Amount|Currency|Amount|VAT|SUM AMT|HB/L No.|MB/L No.|Dept.|P.I.C|';
MSG_KEY['ACC_INV_0090_HDR1'] = '|No.|Client|Client|B/L No.|POL|POD|Volume|Booking|Booking|Booking|Booking|Schedule|Schedule|Schedule|Schedule|Schedule|Shipper|Cnee';
MSG_KEY['ACC_INV_0090_HDR1_1'] = 'CHK|Status|PK|Invoice No.|Customer|Customer|Currency|Invoice Amount|WFG Amount|Settle Amount|Balance Amount|Filing No.|Billing Date|Due Date|Status|Status|Invoice Print|Invoice Cancel|Slip No.|Settle Date|Dept|User|Office|Sell_Buy';
MSG_KEY['ACC_INV_0090_HDR2'] = '|No.|Dept|Name|B/L No.|POL|POD|Volume|Date|No.|Door|Carrier|Vessel|ETD|ETA|ATA|D/O|Shipper|Cnee';
MSG_KEY['ACC_INV_0100_HDR1'] = '|POL||POD|　|　|　|　|　|　|　|　|　|　|　|　|TOTAL';
MSG_KEY['ACC_INV_0100_HDR1_1'] = 'Type|Amount|Check No.|Post Date|Currency';
MSG_KEY['ACC_INV_0100_HDR2'] = '|POL||POD|JAN|FEB|MAR|APR|MAY|JUN|JUL|AUG|SEP|OCT|NOV|DEC|TOTAL';
MSG_KEY['ACC_INV_0110_HDR1'] = 'Date||User|Type|Invoice No.|Amount|Post Date|Invoice Date|Due Date|Customer/Vendor';
MSG_KEY['ACC_INV_0110_HDR2_1'] = 'Seq.|Freight|Freight|P/C|Unit|TP/SZ|Vol.|Rate|Amount|VAT|Curr.|Ex.Rate|Total Amount|Post Date';
MSG_KEY['ACC_INV_0110_HDR2_2'] = 'Seq.|Code|Name|P/C|Unit|TP/SZ|Vol.|Rate|Amount|VAT|Curr.|Ex.Rate|Total Amount|Post Date';
MSG_KEY['ACC_INV_0110_HDR3_1'] = 'Seq.|B/L No.|Freight|Freight|P/C|Unit|TP/SZ|Vol.|Rate|Curr.|Ex.Rate|Debit/Credit|Debit/Credit|Debit/Credit';
MSG_KEY['ACC_INV_0110_HDR3_2'] = 'Seq.|B/L No.|Code|Name|P/C|Unit|TP/SZ|Vol.|Rate|Curr.|Ex.Rate|Rev/Cost|Debit|Credit';
MSG_KEY['ACC_INV_0140_HDR_1'] = '|B/L No.|Post date|BL Staff|Freight|Freight|Freight|CHK|Tax Invoice|Tax Invoice|Tax Invoice|Tax Invoice|Tax Invoice||';
MSG_KEY['ACC_INV_0140_HDR_2'] = '|B/L No.|Post date|BL Staff|Billing code|Currency|Amount|CHK|Paid Cur|Ex.Rate|Inv amount|Tax Ratio|Tax Amount||';
MSG_KEY['ACC_INV_0150_HDR_1'] = 'Seq|B/L No.|Bill to|Inv Title|Tax Invoice no|Issued date|VSL/VOY|POL|POD|Inv Amount|Paid Amt (RMB)|Paid Amt (USD)|Void|Invoice Type|Deposit status||'
MSG_KEY['ACC_JOR_0010_HDR'] = 'DEL|Post Date|Invoice Date|Due Date|Office|Type|G/L No.|G/L No.|Currency|Invoice No.|Invoice No.|Invoice\nAmount|Balance\nAmount|Balance\nAmount|Received|CHK|Ex. Date|Ex. Rate|Ex. Invoice\nAmount|Ex. Received|old_pay_amt|Ex. Rate|Local Amount|Local\nBalance Amount|locl_bal_amt|Local Received|local_pay_amt|Tax Invoice No.|B/L No.|Filing No.|Description|Dept.|Agent Ref. No.|Clear|Clear|inv_seq|jnr_no|jnr_seq|trdp_cd|clr_gl|IBFlag';
MSG_KEY['ACC_JOR_0020_HDR'] = 'Block|CHK|Post Date|Received From|Check No.|Bank|Received Amount|Currency|Deposit\nDate|Void|Void Date|Issued\nOffice|Issued by|HB/L No.|MB/L No.|Other Filing No.|Remark|File|jnr_no|trdp_cd|IBFlag';
MSG_KEY['ACC_JOR_0021_HDR'] = 'Block|CHK|Post Date|Received From|Check No.|Bank|Received Amount|Currency|Deposit\nDate|Void|Void Date|Issued\nOffice|Block|Issued by|Remark|File|jnr_no|trdp_cd|IBFlag';
MSG_KEY['ACC_JOR_0030_HDR'] = 'DEL|Post Date|Invoice Date|Due Date|Office|Type|G/L No.|G/L No.|Currency|Invoice No.|Vendor Invoice No.|Invoice\nAmount|Balance\nAmount|Balance\nAmount|Payment|CHK|Ex. Date|Ex. Rate|Ex. Invoice\nAmount|Ex. Paid|old_pay_amt|Ex. Rate|Local Amount|Local\nBalance Amount|locl_bal_amt|Local Received|local_pay_amt|B/L No.|Filing No.|Description|Dept.|Clear|inv_seq|jnr_no|jnr_seq|trdp_cd|clr_gl|IBFlag||Agent Ref. No.';
MSG_KEY['ACC_JOR_0040_HDR'] = 'Block|CHK|Post Date|Check No.|Vendor|Bank|Paid Amount|Currency|Clear\nDate|Void|Void Date|Issued\nOffice|Print|Rider|Issued by|HB/L No.|MB/L No.|Other Filing No.|Remark|File|jnr_no|trdp_cd|IBFlag';
MSG_KEY['ACC_JOR_0041_HDR'] = 'Block|CHK|Post Date|Check No.|Vendor|Bank|Paid Amount|Currency|Clear\nDate|Void|Void Date|Issued\nOffice|Print|Rider|Block|Issued by|Remark|File|jnr_no|trdp_cd|IBFlag';
MSG_KEY['ACC_JOR_0050_HDR'] = 'DEL|CHK|No.|Description|G/L No.|G/L No.|Original Curr.|Amount|Debit|Credit|Sub|Type|com_cd|Party||User|Debit|Credit|Curr.|Ex.Date|Ex.Rate|g_debit|g_credit|post_dt|dt_seq|p_ofc_cd|rmk|curr_cd|slip_no|slip_seq|IBFlag';
MSG_KEY['ACC_JOR_0051_HDR'] = 'DEL|CHK|No.|Description|G/L No.|G/L No.|Original Curr.|Amount|Debit|Credit|Sub|Type|com_cd|Party||User|Original Debit|Original Credit|Curr.|Ex.Date|Ex.Rate|g_debit|g_credit|post_dt|dt_seq|p_ofc_cd|rmk|curr_cd|slip_no|slip_seq|IBFlag';
MSG_KEY['ACC_JOR_0060_HDR'] = 'CHK|Date|No.|com_cd|Customer|Remark|Office|Debit|Credit|Issued by|slip_no|IBFlag';
MSG_KEY['ACC_JOR_0070_HDR'] = 'Post Date|Bank Name|trdp_cd|Customer|Check No.|Currency|Items|Amount|CHK|void_yn|void_dt|clr_yn|clr_dt|jnr_no|jnr_tp|bank_seq|p_ofc_cd|||clt_cmpl_flg|IBFlag';
MSG_KEY['ACC_JOR_0070_HDR2'] = 'Jnr No.|Clear Dt.|Inv No.|Invoice Type|Customer|Customer|Inv Dt.|B/L No.|Filing No.|Invoice Amount|Paid Amount|Balance Amount';
MSG_KEY['ACC_JOR_0080_HDR'] = 'Bank|Bank|Bank|Book|Book|Book|Book|CHK';
MSG_KEY['ACC_JOR_0080_HDR2'] = 'Date|Check No.|Amount|Post Date|Clear Date|Pay To|Amount|CHK';
MSG_KEY['ACC_JOR_0080_HDR3'] = 'Bank Date|Check No|Bank Amount';
MSG_KEY['ACC_JOR_0100_HDR1'] = 'Bank Name|Office|Deposit|Check Paid|Total|bank_seq|ibflag';
MSG_KEY['ACC_JOR_0120_HDR1'] = 'Post Date|Check No.|Received From|Currency|Amount|Office|Deposit|Deposit Date|Void|Void Date';
MSG_KEY['ACC_JOR_0120_HDR2'] = 'Post Date|Check No.|Pay To|Currency|Amount|Office|Clear|Clear Date|Void|Void Date';
MSG_KEY['ACC_JOR_0150_HDR1'] = 'Type|Inv Date|Post Date|Inv No.||Name of Customer||||Payment Term|Amount|Paid|Over 1-30 Days|Over 31-60 Days|Over 61-90 Days|Over 91 Days|Created by|Received Date||';
MSG_KEY['ACC_JOR_0200_HDR'] = 'DEL|CHK|Billing Date|Office|Dept.|Type|Invoice No.|Invoice No.|Currency|Ex. Rate|Invoice\nAmount|Balance\nAmount|Received|Received\nAmount|old_pay_amt|G/L No.|G/L No.|Filing No.|B/L No.|Description|Clear|inv_seq|jnr_no|jnr_seq|trdp_cd|clr_gl|IBFlag';
MSG_KEY['ACC_JOR_0210_HDR'] = 'DEL|CHK|Billing Date|Office|Dept.|Type|Invoice No.|Invoice No.|Currency|Ex. Rate|Invoice\nAmount|Balance\nAmount|Payment|Payment\nAmount|old_pay_amt|G/L No.|G/L No.|Filing No.|B/L No.|Description|Clear|inv_seq|jnr_no|jnr_seq|trdp_cd|clr_gl|IBFlag';
MSG_KEY['ACC_JOR_0500_HDR1'] = 'CHK|Customer|Invoice No.|Post Date|Invoice Date|Due Date|Office|Dept.|Type|Currency|Ex. Rate|Invoice No.|Invoice\nAmount|Balance\nAmount|Ex. Date|Ex. Rate|Ex. Invoice\nAmount|G/L No.|G/L No.|Filing No.|B/L No.|||||Account Group ID|Agent Ref. No.';
MSG_KEY['ACC_JOR_0600_HDR'] = 'No.|Invoice\nDate|Due\nDate|Customer/Vendor|Department|Type|Tax Invoice No.|Invoice No.|Filing No.|B/L No.|Curr.|INV_SEQ|Invoice\nAmount|Balance\nAmount|Paid\nAmount|Paid Date|Bank|Check No.|Bank\nDate|Void\nDate';
MSG_KEY['ACC_JOR_0610_HDR1'] = 'Check Information|Check Information|Check Information|Check Information|Check Information|Check Information|Check Information|Check Information|Check Information|Check Information|Check Information|Invoice Information|Invoice Information|Invoice Information|Invoice Information|Invoice Information|Invoice Information|Invoice Information|Invoice Information|Invoice Information|Invoice Information|Invoice Information|Invoice Information|Invoice Information|Invoice Information';
MSG_KEY['ACC_JOR_0610_HDR2'] = 'jnr_no|Post Date|Type|Bank|Office|Customer/Vendor|Check#|Amount|Curr.|Clear|Void|Tax Invoice No.|Curr.|Invoice No.|Post Date|Invoice\nDate|Due Date|Office|Type|Invoice\nAmount|Paid\nAmount|Balance\nAmount|G/L No.|G/L No.|Description';
MSG_KEY['ACC_JOR_0630_HDR1'] = '||Department|Office|Operator|Filing No.|MBL No.|HBL No.|B/L Type|Sales Type|ETD|ETA|Post Date|A/R Invoice No.|Currency|Amount|Create Date|Create Date|Gap';
MSG_KEY['ACC_JOR_0700_HDR1'] = 'Date|User|Type|Customer /\nVendor|Received From /\nPaid To|Post Date|Currency|Bank|Check No.|Amount|Clear Date|Void Date||';
MSG_KEY['ACC_JOR_0700_HDR2'] = 'Seq.|Post Date|Office|Type|G/L No.|G/L No.|Currency|Ex.Rate|Invoice No.|Invoice\nAmount|Received|Ex. Date|Ex. Rate|Ex. Invoice\nAmount|Received\nAmount|Ex. Received|B/L No.|Filing No.|Description|Dept.';
MSG_KEY['ACC_JOR_0700_HDR3'] = 'Seq.|Post Date|Office|Type|G/L No.|G/L No.|Currency|Ex.Rate|Invoice No.|Invoice\nAmount|Payment|Ex. Date|Ex. Rate|Ex. Invoice\nAmount|Paid\nAmount|Ex. Paid|B/L No.|Filing No.|Description|Dept.';
MSG_KEY['ACC_JOR_0800_HDR1'] = 'Type|Currency|Received\nAmount|Collected\nAmount|Original Collected\nAmount|Exchange\nGain/Loss|Bank|Check No.|Post Date|Old Post Date|Clear|Clear Date|Void|Old Void|Void Date|Old Void Date|jnr_no|Group Slip No|Office|Customer Code|Customer Name|Block YN|Current Check No|Last Check No|IBFlag';
MSG_KEY['ACC_JOR_0800_HDR2_1'] = 'DEL|Post\nDate|Invoice\nDate|Due\nDate|Office|Staff|Type|G/L No.|G/L No.|Invoice|Invoice|Invoice|Invoice|Invoice|Invoice|Invoice|Collected|Collected|Collected|Collected|Collected|Collected|Collected|old_pay_amt|Verify|Pay|B/L No.|Filing No.|Block|Description|Dept.|inv_seq|jnr_no|jnr_seq|trdp_cd|clr_gl|IBFlag';
MSG_KEY['ACC_JOR_0800_HDR2_2'] = 'DEL|Post\nDate|Invoice\nDate|Due\nDate|Office|Staff|Type|G/L No.|G/L No.|Vendor Invoice No.|Invoice No.|Memo|Currency|Amount|Balance|Balance|Amount|CHK|Currency|Ex.Date|Ex.Rate|inv_xcrt_sum_amt|Total|old_pay_amt|Verify|Pay|B/L No.|Filing No.|Block|Description|Dept.|inv_seq|jnr_no|jnr_seq|trdp_cd|clr_gl|IBFlag';
MSG_KEY['ACC_JOR_0810_HDR'] = 'Block|CHK|Slip No.|Post Date|Check No.|Received/Remit To|Bank|Curr.|Amount|Clear Date|Void|Void Date|Print|Rider|Issued Office|Issued by|Voucher Type|Voucher No.|Audit|Audit by|Audit at|Receive Type|HB/L No.|MB/L No.|Other Filing No.|Remark|jnr_no|trdp_cd|IBFlag';
MSG_KEY['ACC_PER_0010_HDR1'] = 'Partner|House B/L|Master B/L|Bkg. No.|Work Order|POL|POD';
MSG_KEY['ACC_SLP_0010_HDR1'] = 'inv_crt|inv_dept|inv_void|ap_crt|ap_dept|ap_void|cd_crt|cd_dept|cd_void|dept_crt|dept_dept|dept_void|chk_crt|chk_dept|chk_void|tot_crt|tot_dept|tot_void|clt_cmpl_flg|ibflag';
MSG_KEY['ACC_SLP_0010_HDR2'] = 'Type|Filing No.|Post Date|Trade Partner|Trade Partner|G/L No.|Currency|Amount|Office|Ref. Seq|Error';
MSG_KEY['ACC_SLP_0020_HDR1'] = 'inv_crt|inv_dept|inv_void|ap_crt|ap_dept|ap_void|cd_crt|cd_dept|cd_void|dept_crt|dept_dept|dept_void|chk_crt|chk_dept|chk_void|tot_crt|tot_dept|tot_void|ibflag';
MSG_KEY['ACC_SLP_0030_HDR'] = 'CHK|Block|Post Date|Seq|Invoice Date|Slip No.|Seq|Type/Party|Type/Party|com_cd||User|Currency|Debit|Credit|Remark|I/F Y/N|Issued by|Office|Deleted|Audit|Audit by|Audit at|||||||||Voucher No.|Voucher Type|IBFlag';
MSG_KEY['ACC_SLP_0040_HDR1_1'] = 'CHK|Type|Slip No.|Slip No.|G/L|G/L|Acct. G/L|Acct. G/L|Debit|Credit|Currency|Ex. Rate|Total|Total|Description|Acct. Slip No.|Acct. Slip No.';
MSG_KEY['ACC_SLP_0040_HDR1_2'] = 'CHK|Type|No.|Seq.|No.|Desc.|No.|Desc.|Debit|Credit|Currency|Ex. Rate|Debit|Credit|Description|No.|Seq.';
MSG_KEY['ACC_SLP_0050_HDR1'] = 'CHK|Code|Name(Eng)|Name(Local)|Local Address|B/L Address|Office|Biz No.|Rgst Time|rtn_flag|ibflag';
MSG_KEY['ACC_SLP_0060_HDR1'] = 'Type|Slip No.|Seq.|Invoice Date|Cust Code|Cust Name|Ex. Rate|Amt|Debit|Credit|Description|O.Slip No.|tp_drcr|ibflag';
MSG_KEY['ACC_SLP_0070_HDR1'] = 'Office|Last Block Date';
MSG_KEY['ACC_SLP_0080_HDR1'] = 'No.|Block|Dept.|Office|Post Date|Filing No.|B/L No.|Shipper|Consignee|Agent|POL|POD|Vessel/FLT No.';
MSG_KEY['ACC_SLP_0080_HDR2'] = 'No.|Block|Type|Office|Post Date|Invoice No.|Tax Invoice No.|Bill To/Pay To|Currency|Invoice Amount|Filing No.|MB/L No.|HB/L No.|Other Filing No.';
MSG_KEY['ACC_SLP_0080_HDR3'] = 'No.|Block|Type|Issued Office|Post Date|Bank|Check No.|Currency|Amount|Received From/Pay To';
MSG_KEY['ACC_SLP_0080_HDR4'] = 'No.|Block|Type|Office|Post Date|Invoice Date|Currency|Remark|Debit|Credit|Issued by';
MSG_KEY['ACC_SLP_0100_HDR1'] = 'No.|Program|Block Type|Ref No.|Remark|Executed by|Date Executed|Office';
MSG_KEY['ACC_COM_ALT001'] = 'A/P cannot be Output! '; //Account Payable 는 인쇄할수 없습니다.
MSG_KEY['ACC_COM_ALT002'] = 'Trade Partner does not exist, Please check again! '; //거래처가 존재하지 않습니다. 다시 확인하여 주시기 바랍니다!
MSG_KEY['ACC_COM_ALT003'] = 'S/R can only be grouped in the case of same Vessle or same Voyage! '; //Vessel 또는 Voyage가 동일해야 하나의 Shipping Request로 묶일 수 있습니다!
MSG_KEY['ACC_COM_ALT004'] = 'Invoice can be cancelled when the status of the Invoice is Issued! '; //Invoice 상태가 Issue인 경우에만 취소할 수 있습니다!
MSG_KEY['ACC_COM_ALT005'] = 'Please select the Customer first! ';
MSG_KEY['ACC_COM_ALT006'] = 'Debit/Credit does not match! ';
MSG_KEY['ACC_COM_ALT007'] = 'No modified data.';
MSG_KEY['ACC_COM_ALT008'] = '[Warning] Both MB/L and HB/L do not exist! ';
MSG_KEY['ACC_COM_ALT009'] = '[Warning] The B/L No. does not exist! ';
MSG_KEY['ACC_COM_ALT010'] = '[Warning] B/L No. is missing. Would you like to proceed anyway? ';
MSG_KEY['ACC_COM_ALT011'] = ' cases are not valid! '; //**건이 유효하지 않습니다!
MSG_KEY['ACC_COM_ALT012'] = '[Warning] The Check No. is missing. Do you want to save? ';
MSG_KEY['ACC_COM_ALT013'] = '[Warning] The Check No. is a duplicate. Do you want to save? ';
MSG_KEY['ACC_COM_ALT014'] = '[Warning] Some Invoices have no invoice numbers. Would you like to proceed anyway? ';
MSG_KEY['ACC_COM_ALT015'] = '[Warning] Invoice No. does not exist! ';
MSG_KEY['ACC_COM_ALT016'] = 'Do you want to change the status from Hold to Release?';
MSG_KEY['ACC_COM_ALT017'] = 'Do you want to change the status from Release to Hold?';
MSG_KEY['ACC_INV_0021_MSG1'] = 'You are allowed to add after saving the modified items!';
MSG_KEY['ACC_INV_0021_MSG2'] = 'You are allowed to add after saving the modified items!';
MSG_KEY['ACC_INV_0021_MSG3'] = 'There is a row added. Please enter values before adding rows.';
MSG_KEY['ACC_INV_0021_MSG4'] = 'Sum of the collection of money is higher than the requested one. Please confirm.';
MSG_KEY['ACC_INV_0031_MSG01'] = 'Duplicated Invoice Number Found.\nWould you like to continue to use same Invoice Number?';
MSG_KEY['ACC_INV_0080_MSG01'] = 'Please enter a Customer!';
MSG_KEY['ACC_MSG100'] = 'October already Journalized !!';
MSG_KEY['ACC_MSG101'] = 'November already Journalized !!';
MSG_KEY['ACC_MSG102'] = 'December already Journalized !!';
MSG_KEY['ACC_MSG103'] = 'Please search the data in advance!';
MSG_KEY['ACC_MSG104'] = 'The End Date must be greater than or equal to the Start Date.';
MSG_KEY['ACC_MSG105'] = 'No checked data.';
MSG_KEY['ACC_MSG106'] = 'There is no data to save.';
MSG_KEY['ACC_MSG107'] = 'Please select the AR/AP List in advance!';
MSG_KEY['ACC_MSG108'] = 'Please select Report Type.';
MSG_KEY['ACC_MSG109'] = 'Please select Bank.';
MSG_KEY['ACC_MSG110'] = 'The G/L of @:@ is missing.';
MSG_KEY['ACC_MSG111'] = 'Selected Type/Size is already in use. Please select another Type/Size or Freight Code!';
MSG_KEY['ACC_MSG112'] = 'The Data is not checked.';
MSG_KEY['ACC_MSG113'] = 'The Container Date does not exist on this B/L. Please check the [Container] tab on the B/L.';
MSG_KEY['ACC_MSG114'] = 'Payment amout is already exist !'; //[20130401 OJG]
MSG_KEY['ACC_MSG115'] = 'The Current Check number is larger than the last Check number. Proceed anyway?'; //[20130731 OJG]
MSG_KEY['ACC_MSG116'] = 'Please check Bank Setup!'; //[20130808 OJG]
MSG_KEY['ACC_MSG117'] = 'Please input the last date of the month!';
MSG_KEY['ACC_MSG118'] = 'The adjusted amount must be greater than paid amount.';
MSG_KEY['ACC_MSG119'] = 'The Post Date must be later than the block date (@).';
MSG_KEY['ACC_MSG120'] = 'Please check the search condition(s).';
MSG_KEY['ACC_MSG121'] = 'The Block Date is a mandatory field.';
MSG_KEY['ACC_MSG122'] = 'The Block Date must be later than the post date.';
MSG_KEY['ACC_MSG123'] = 'The Processing Year must be one year later than the last processed End Year.';
MSG_KEY['ACC_MSG124'] = 'The amount of some items is 0. Delete these items?';
MSG_KEY['ACC_MSG125'] = 'Post Date is a mandatory field.';
MSG_KEY['ACC_MSG126'] = 'The Void Date must be later than or equal to the Post date.';
MSG_KEY['ACC_MSG127'] = 'The Deposit Date must be later than or equal to the Post date.';
MSG_KEY['ACC_MSG128'] = 'This invoice has been updated by other transactions.\nPlease reload .';
MSG_KEY['ACC_MSG129'] = 'The Void Date must be later than the block date (@).';
MSG_KEY['ACC_MSG130'] = "The Void Date must be later than or equal to Today's date.";
MSG_KEY['ACC_MSG131'] = 'The Deposit Date must be later than the block date (@).';
MSG_KEY['ACC_MSG132'] = "The Deposit Date must be later than or equal to the Today's date.";
MSG_KEY['ACC_MSG133'] = 'The check number is missing.';
MSG_KEY['ACC_MSG134'] = 'The Payment Amount could not be greater than the Invoice Amount.';
MSG_KEY['ACC_MSG135'] = 'You cannot delete all items.';
MSG_KEY['ACC_MSG136'] = 'The Void Date must be later than or equal the @.';
MSG_KEY['ACC_MSG137'] = 'The amount of some invoices (@) has exceeded the Balance Amount. Proceed anyway?';
MSG_KEY['ACC_MSG138'] = 'This cannot be deleted because it has already been voided.';
MSG_KEY['ACC_MSG139'] = 'Please check the Bank Currency.';
MSG_KEY['ACC_MSG140'] = 'You cannot delete the data';
MSG_KEY['ACC_MSG141'] = 'You cannot save the data';
MSG_KEY['ACC_MSG142'] = 'It cannot be deleted because there exists an amount paid';
MSG_KEY['ACC_MSG143'] = 'It cannot be modified because there exists an amount paid';
MSG_KEY['ACC_MSG144'] = 'These invoices have been updated by other transactions.\nPlease reload .';
MSG_KEY['ACC_MSG145'] = 'The Processing Month must be one month later than the last processed End Month.';
MSG_KEY['ACC_MSG146'] = 'Would you like to change the Exchange Rate Date?';
MSG_KEY['ACC_MSG147'] = 'Please reload before making any revision.';
MSG_KEY['ACC_MSG148'] = 'Apply Date must be greater than Last Block Date.';
MSG_KEY['ACC_MSG149'] = 'Apply Date must be smaller than Last Block Date.';
MSG_KEY['ACC_MSG150'] = 'please try again after blocking all data.';
MSG_KEY['ACC_MSG151'] = 'It is not able to unblock data prior to Year-End Date(@).\nPlease cancel Year-End in advance.';
MSG_KEY['ACC_MSG152'] = 'There is no G/L No.';
MSG_KEY['ACC_MSG153'] = 'Deposit has already been blocked.';
MSG_KEY['ACC_MSG154'] = 'Payment has already been blocked.';
MSG_KEY['ACC_MSG155'] = 'Journal has already been blocked.';
MSG_KEY['ACC_MSG156'] = 'Journal has already been voided.';
MSG_KEY['ACC_MSG157'] = 'Journal has already been closeed.';
MSG_KEY['ACC_MSG24'] = 'Void checked! ';
MSG_KEY['ACC_MSG25'] = 'No Printable Data! ';
MSG_KEY['ACC_MSG26'] = 'Select the Vendor in advance! ';
MSG_KEY['ACC_MSG27'] = 'Bank is a mandatory field. ';
MSG_KEY['ACC_MSG28'] = 'Invalid Clear Date';
MSG_KEY['ACC_MSG29'] = 'G/L No. is a mandatory field. ';
MSG_KEY['ACC_MSG30'] = 'Please check the Transaction Entity (Customer).  ';
MSG_KEY['ACC_MSG32'] = 'Date is a mandatory field. ';
MSG_KEY['ACC_MSG33'] = 'There is no data';
MSG_KEY['ACC_MSG34'] = 'Please select the Batch Type. ';
MSG_KEY['ACC_MSG35'] = 'Pease input the Deposit/Clear Date in advance! ';
MSG_KEY['ACC_MSG36'] = 'The Deposit/Clear Date is earlier than the Post Date!';
MSG_KEY['ACC_MSG37'] = 'Period is a mandatory field. ';
MSG_KEY['ACC_MSG38'] = 'Please Print After Retrieve!';
MSG_KEY['ACC_MSG39'] = 'Aging Report Type is a mandatory field.';
MSG_KEY['ACC_MSG40'] = 'Department Type is a mandatory field.';
MSG_KEY['ACC_MSG41'] = 'Ending Date is a mandatory field.';
MSG_KEY['ACC_MSG42'] = 'Data Range is a mandatory field. ';
MSG_KEY['ACC_MSG43'] = 'Please refresh the screen!';
MSG_KEY['ACC_MSG44'] = 'Processing… Please wait!';
MSG_KEY['ACC_MSG45'] = 'Please input the correct Start Date! ';
MSG_KEY['ACC_MSG46'] = 'Please input the correct End Date! ';
MSG_KEY['ACC_MSG47'] = 'Please select the preferred Slip Type. ';
MSG_KEY['ACC_MSG48'] = 'Processing date is a mandatory field. ';
MSG_KEY['ACC_MSG49'] = 'Please select the preferred Acct. Company.';
MSG_KEY['ACC_MSG50'] = 'Please select the preferred Currency.';
MSG_KEY['ACC_MSG51'] = 'January not closed! ';
MSG_KEY['ACC_MSG52'] = 'February not Closed !! ';
MSG_KEY['ACC_MSG53'] = 'March not Closed !! ';
MSG_KEY['ACC_MSG54'] = 'April not Closed !! ';
MSG_KEY['ACC_MSG55'] = 'May not Closed !! ';
MSG_KEY['ACC_MSG56'] = 'June not Closed !! ';
MSG_KEY['ACC_MSG57'] = 'July not Closed !! ';
MSG_KEY['ACC_MSG58'] = 'August not Closed !! ';
MSG_KEY['ACC_MSG59'] = 'September not Closed !! ';
MSG_KEY['ACC_MSG60'] = 'October not Closed !! ';
MSG_KEY['ACC_MSG61'] = 'November not Closed !! ';
MSG_KEY['ACC_MSG62'] = 'December not Closed !! ';
MSG_KEY['ACC_MSG63'] = 'Please verify first! '; //먼저 Verify 작업을 진행해 주십시요
MSG_KEY['ACC_MSG64'] = 'Invalid Data! '; //유효하지 않은 Data 입니다.
MSG_KEY['ACC_MSG65'] = 'No data found! '; //Interface할 데이터가 없습니다.
MSG_KEY['ACC_MSG66'] = 'Please input the Ex. Rate.';
MSG_KEY['ACC_MSG67'] = 'Completed! '; //건이 적용되었습니다.
MSG_KEY['ACC_MSG68'] = 'Not available! '; //건이 유효하지 않습니다.
MSG_KEY['ACC_MSG69'] = 'All data is OK! '; //모든 데이터가 정상입니다.
MSG_KEY['ACC_MSG70'] = 'Please enter a Value'; //Acct. Company 를 입력해 주십시요.
MSG_KEY['ACC_MSG71'] = 'January already Journalized !! ';
MSG_KEY['ACC_MSG72'] = 'February already Journalized !! ';
MSG_KEY['ACC_MSG73'] = 'March already Journalized !! ';
MSG_KEY['ACC_MSG74'] = 'April already Journalized !! ';
MSG_KEY['ACC_MSG75'] = 'May already Journalized !! ';
MSG_KEY['ACC_MSG76'] = 'June already Journalized !! ';
MSG_KEY['ACC_MSG77'] = 'July already Journalized !! ';
MSG_KEY['ACC_MSG78'] = 'August already Journalized !! ';
MSG_KEY['ACC_MSG79'] = 'September already Journalized !! ';
MSG_KEY['ACC_MSG80'] = 'October already Journalized !! ';
MSG_KEY['ACC_MSG81'] = 'November already Journalized !! ';
MSG_KEY['ACC_MSG82'] = 'December already Journalized !! ';
MSG_KEY['ACC_MSG83'] = 'Completed! '; //정상처리 되었습니다.
MSG_KEY['ACC_MSG84'] = 'The Debit and Credit amounts are different! '; //Debit 금액과 Credit 금액의 차액이 발생했습니다.
MSG_KEY['ACC_MSG85'] = 'The total pay amount is less than 0. Proceed anyway?';
MSG_KEY['ACC_MSG91'] = 'January already Journalized !!';
MSG_KEY['ACC_MSG92'] = 'February already Journalized !!';
MSG_KEY['ACC_MSG93'] = 'March already Journalized !!';
MSG_KEY['ACC_MSG94'] = 'April already Journalized !!';
MSG_KEY['ACC_MSG95'] = 'May already Journalized !!';
MSG_KEY['ACC_MSG96'] = 'June already Journalized !!';
MSG_KEY['ACC_MSG97'] = 'July already Journalized !!';
MSG_KEY['ACC_MSG98'] = 'August already Journalized !!';
MSG_KEY['ACC_MSG99'] = 'September already Journalized !!';

//#1428 [PATENT] 0215_12 VERIFY PAYMENT SCREEN - Last Paid Date
MSG_KEY['ACC_INV_0130_HDR1'] = 'ibflag|intg_bl_seq|No.|Sales PIC|Billng Carrier Cd|Billng Carrier|Filing No.|Type|B/L No.|Verify_By|Verify|Verified at|Pay|Paid at|Onboard|ETD|ETA|Hold|Hold at|Hold Reason|Release|Release Type|Released at|Shipper Cd|Shipper|Consignee Cd|Consignee|Customer Cd|Customer|Partner Cd|Partner|VSL/VOY|POL cd|POL|POD cd|POD|Issued by|Issued at|';
MSG_KEY['ACC_INV_0130_HDR2'] = 'inv_seq|No.|B/L Type|B/L No.|Type|Invoice No.|Remit to|Item Description|Curr.|Rate Amount|PMT|Last P.Date';
MSG_KEY['ACC_INV_0130_HDR3'] = 'cntr_list_seq|B/L No.|Container No.|Ref. No.|TP/SZ|Package|Package|WGT(KG)|WGT(LB)|CBM|CFT|Remark';

//#2203 [LBS] Batch Processing Validation 강화
//#3004 [BNX] SYTEM VALIDATION MSG TYPO ERROR
MSG_KEY['ACC_MSG158'] = 'Some data have been updated by other transactions.\nPlease refresh and try saving again. ';
MSG_KEY['ACC_SLP_0120_HDR1'] = 'From|Last Exchange Rate|Adjusted Exchange Rate';

MSG_KEY['ACC_MSG159'] = 'Please, select check box of freight item to split';
MSG_KEY['ACC_MSG160'] = 'Invoice has already been blocked.';
MSG_KEY['ACC_MSG161'] = 'Do you want to split? ';
MSG_KEY['ACC_MSG162'] = 'Invoice has already been paid? ';
MSG_KEY['ACC_MSG163'] = 'Processing Month must be greater than Last Processed Month ';
MSG_KEY['ACC_PROCEMH'] = 'Processing Month';
MSG_KEY['ACC_MSG164'] = 'Please enter a Exchange Rate at the Monthly Exchange Profit Adjustment';
MSG_KEY['ACC_MSG165'] = 'Please input the Last Adjusted Exchange Rate.';
//#1165 : [Sales Mexico/Germany] VAT Calculation is not working
MSG_KEY['ACC_MSG166'] = 'There is no VAT code assigned on this operation. \nPlease, setup the VAT information from the code.';
//#3505 [JTC]ACCT - Local Currency 금액 환산 & SLIP 반영
MSG_KEY['ACC_MSG167'] = 'Please input \"Invoice exchange rate\"!';
MSG_KEY['ACC_MSG168'] = 'Please, input the Received Amount first when you select different currency bewteen bank and invoice!';
MSG_KEY['ACC_MSG169'] = 'It cannot be deleted because invoice is blocked.';
MSG_KEY['ACC_MSG170'] = "You are not authorized to create or edit other Office's Accounting data. Please check with Admin for role setting.";
//
MSG_KEY['ACC_MSG171'] = "Invoice should only include single currency freights.\nThere is multiple currency freights exist.\nPlease check on BL Entry screen - Freight tab.";
MSG_KEY['ACC_MSG172'] = "This B/L exceeds the credit limit. \nPlease contact Accounting Manager";
//OFVFOUR-7147 [ACL US] Other BL deleted after invoice created
MSG_KEY['ACC_MSG173'] = 'This Other BL is deleted already so cannot create Invoice';
MSG_KEY['ACC_MSG174'] = 'This BL is deleted already so cannot create Invoice';
//OFVFOUR-6462 [NTL]BALANCE SHEET & INCOME STATEMENT missmatch - Retained Earning Check Logic.
MSG_KEY['ACC_MSG175'] = 'There is no Retained Earning No. \nPlease input Retained Earning No. for Office: ';